--=======================================================================================
-- Generated by TypescriptToLua transpiler https://github.com/Perryvw/TypescriptToLua
-- Date: Sun May 13 2018
--=======================================================================================
require("typescript_lualib")
LinkLuaModifier("modifier_day_night","abilities/mutators/modifier_vampirism_mutator.lua",LUA_MODIFIER_MOTION_NONE)
modifier_vampirism_mutator = {}
modifier_vampirism_mutator.__index = modifier_vampirism_mutator
function modifier_vampirism_mutator.new(construct, ...)
    local instance = setmetatable({}, modifier_vampirism_mutator)
    if construct and modifier_vampirism_mutator.constructor then modifier_vampirism_mutator.constructor(instance, ...) end
    return instance
end
function modifier_vampirism_mutator.IsPermanent(self)
    return true
end
function modifier_vampirism_mutator.IsPurgable(self)
    return false
end

function modifier_vampirism_mutator.GetTexture(self)
    return "custom/modifier_vampirism_mutator"
end

function modifier_vampirism_mutator.OnCreated(self)
    self.daytime_hp_drain = 1
    self.night_lifesteal = 20
    self.night_bonus_ms = 10
    self.night_mana_regen = 1
    self.lifesteal_penalty_against_creeps = 40
	self.spell_lifesteal_penalty_against_creeps = 80

    if IsServer() then
        self:StartIntervalThink(FrameTime())

        self:GetParent():AddNewModifier(self:GetParent(),nil,"modifier_day_night",{})
    end
end

function modifier_vampirism_mutator.OnIntervalThink(self)
    self.dayTime = GameRules:IsDaytime()
    self.oldDayTime = self.oldDayTime or self.dayTime

    if self.dayTime ~= self.oldDayTime then
        if self.dayTime == false then
            Notifications:Top(self:GetParent():GetPlayerOwner(),{text="THE NIGHT HAS COME!",duration = 5})
        else
            Notifications:Top(self:GetParent():GetPlayerOwner(),{text="THE NIGHT IS OVER!",duration = 5})
        end
    end
    self.oldDayTime = self.dayTime

end

function modifier_vampirism_mutator.DeclareFunctions(self)
    return {
        MODIFIER_PROPERTY_HEALTH_REGEN_PERCENTAGE,
        MODIFIER_EVENT_ON_TAKEDAMAGE,
        MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE,
        MODIFIER_PROPERTY_MANA_REGEN_TOTAL_PERCENTAGE,
    }
end

function modifier_vampirism_mutator.GetModifierMoveSpeedBonus_Percentage(self)

    if self:GetParent():GetModifierStackCount("modifier_day_night",self:GetParent()) == 0 then
        return 0
    else
        return self.night_bonus_ms
    end
end

function modifier_vampirism_mutator.GetModifierHealthRegenPercentage(self)
    if self:GetParent():GetModifierStackCount("modifier_day_night",self:GetParent()) == 0 then
        return -1
    else
        return 1
    end
end

function modifier_vampirism_mutator.GetModifierTotalPercentageManaRegen(self)
    if self:GetParent():GetModifierStackCount("modifier_day_night",self:GetParent()) == 0 then
        return 0
    else
        return 1
    end
end

if IsServer() then
    function modifier_vampirism_mutator:OnTakeDamage(event)
        local parent = self:GetParent()
        local attacker = event.attacker
        local damaged_unit = event.unit
        local dmg_flags = event.damage_flags
        local damage = event.damage
        local inflictor = event.inflictor
        local dmg_type = event.damage_type

        -- Check if attacker exists
        if not attacker or attacker:IsNull() then
            return
        end

        -- Does not work during the day
        if GameRules:IsDaytime() then
            return
        end

        -- Check if attacker has this modifier
        if attacker ~= parent then
            return
        end

        -- Check if damaged entity exists
        if not damaged_unit or damaged_unit:IsNull() then
            return
        end

        -- Ignore self damage
        if damaged_unit == attacker then
            return
        end

        -- Check if entity is an item, rune or something weird
        if damaged_unit.GetUnitName == nil then
            return
        end

        -- Buildings, wards and illusions can't lifesteal
		if attacker:IsTower() or attacker:IsBarracks() or attacker:IsBuilding() or attacker:IsOther() or attacker:IsIllusion() then
			return
		end

        -- Don't affect buildings, wards and invulnerable units.
        if damaged_unit:IsTower() or damaged_unit:IsBarracks() or damaged_unit:IsBuilding() or damaged_unit:IsOther() or damaged_unit:IsInvulnerable() then
            return
        end

        local succubus = attacker:FindAbilityByName("queenofpain_succubus")
        local isSuccubus = succubus and succubus:GetLevel() > 0
        local spellLifestealReflected = false
        if isSuccubus then
            spellLifestealReflected = succubus:GetSpecialValueFor("lifesteal_reflected") == 1
        end

        -- Ignore pure damage
        --if dmg_type == DAMAGE_TYPE_PURE then
            --if not isSuccubus then
                --return
            --end
        --end

        -- Ignore damage that has the no-reflect flag
        if bit.band(dmg_flags, DOTA_DAMAGE_FLAG_REFLECTION) > 0 then
            -- Bondage spell lifesteal for reflected dmg only works if dmg is magical or pure
            if dmg_type ~= DAMAGE_TYPE_MAGICAL and dmg_type ~= DAMAGE_TYPE_PURE then
                return
            end
            if not spellLifestealReflected then
                return
            end
        end

        -- Ignore damage that has the no-spell-lifesteal flag
        if bit.band(dmg_flags, DOTA_DAMAGE_FLAG_NO_SPELL_LIFESTEAL) > 0 then
            -- Bondage spell lifesteal for reflected dmg only works if dmg is magical or pure
            if dmg_type ~= DAMAGE_TYPE_MAGICAL and dmg_type ~= DAMAGE_TYPE_PURE then
                return
            end
            if not spellLifestealReflected then
                return
            end
        end

        -- Ignore damage with HP removal flag
        if bit.band(dmg_flags, DOTA_DAMAGE_FLAG_HPLOSS) > 0 then
            return
        end

        -- Ignore damage with no-spell-amplification flag
        --if bit.band(dmg_flags, DOTA_DAMAGE_FLAG_NO_SPELL_AMPLIFICATION) > 0 then
            --return
        --end

        -- Don't heal while dead
        if not attacker:IsAlive() then
            return
        end

        -- Check damage if 0 or negative
        if damage <= 0 then
            return
        end

        -- Calculate the lifesteal (heal) amount
        local lifesteal_amount = 0
        local spell_lifesteal_amount = 0
        if damaged_unit:IsRealHero() or damaged_unit:IsStrongIllusionCustom() then
            lifesteal_amount = damage * self.night_lifesteal / 100
            spell_lifesteal_amount = damage * self.night_lifesteal / 100
        else
            -- Illusions are treated as creeps too
            lifesteal_amount = damage * (self.night_lifesteal / 100) * (1 - self.lifesteal_penalty_against_creeps / 100)
            spell_lifesteal_amount = damage * (self.night_lifesteal / 100) * (1 - self.spell_lifesteal_penalty_against_creeps / 100)
        end

        -- Particle and health restoration
        if inflictor and spell_lifesteal_amount > 0 then
            -- Spell Lifesteal
            attacker:HealWithParams(spell_lifesteal_amount, inflictor, false, true, attacker, true)
            local particle1 = ParticleManager:CreateParticle("particles/items3_fx/octarine_core_lifesteal.vpcf", PATTACH_ABSORIGIN_FOLLOW, attacker)
            ParticleManager:SetParticleControl(particle1, 0, attacker:GetAbsOrigin())
            ParticleManager:ReleaseParticleIndex(particle1)
        end
        if not inflictor and lifesteal_amount > 0 then
            -- Normal Lifesteal
            attacker:HealWithParams(lifesteal_amount, nil, true, true, attacker, false)
            local particle2 = ParticleManager:CreateParticle("particles/generic_gameplay/generic_lifesteal.vpcf", PATTACH_ABSORIGIN_FOLLOW, attacker)
            ParticleManager:ReleaseParticleIndex(particle2)
        end
    end
end


modifier_day_night = class({})
function modifier_day_night:IsHidden() return true end
function modifier_day_night:IsPermanent() return true end

function modifier_day_night:OnCreated()
    if IsServer() then
        self:StartIntervalThink(FrameTime())
    end
end

function modifier_day_night:OnIntervalThink()
    if GameRules:IsDaytime() then
        self:SetStackCount(0)
    else
        self:SetStackCount(1)
    end
end
