--=======================================================================================
-- Generated by TypescriptToLua transpiler https://github.com/Perryvw/TypescriptToLua
-- Date: Sun May 13 2018
--=======================================================================================
require("typescript_lualib")

modifier_random_lane_creep_spawner_mutator = {}
modifier_random_lane_creep_spawner_mutator.__index = modifier_random_lane_creep_spawner_mutator
function modifier_random_lane_creep_spawner_mutator.new(construct, ...)
    local instance = setmetatable({}, modifier_random_lane_creep_spawner_mutator)
    if construct and modifier_random_lane_creep_spawner_mutator.constructor then modifier_random_lane_creep_spawner_mutator.constructor(instance, ...) end
    return instance
end
function modifier_random_lane_creep_spawner_mutator.IsPermanent(self)
    return true
end
function modifier_random_lane_creep_spawner_mutator.IsPurgable(self)
    return false
end
function modifier_random_lane_creep_spawner_mutator.IsHidden(self)
    return true
end
function modifier_random_lane_creep_spawner_mutator:OnCreated()
    if IsServer() then
        if OptionManager:GetOption("randomLaneCreeps") == 1 then
            self.maxSpawn = 2
            self.minSpawn = 0
        elseif OptionManager:GetOption("randomLaneCreeps") == 2 then
            self.maxSpawn = 4
            self.minSpawn = 2
        end

        print("modifier_random_lane_creep_spawner_mutator")

        self.units = {
            "npc_dota_neutral_redux_centaur_khan",
            "npc_dota_neutral_redux_polar_furbolg_ursa_warrior",
            "npc_dota_neutral_redux_alpha_wolf",
            "npc_dota_neutral_redux_enraged_wildkin",
            "npc_dota_neutral_redux_satyr_soulstealer",
            "npc_dota_neutral_redux_satyr_hellcaller",
            "npc_dota_neutral_redux_satyr_trickster",
            "npc_dota_neutral_redux_dark_troll_warlord",
            "npc_dota_neutral_redux_black_dragon",
            "npc_dota_neutral_redux_black_drake",
            "npc_dota_neutral_redux_harpy_storm",
            "npc_dota_neutral_redux_harpy_scout",
            "npc_dota_neutral_redux_forest_troll_high_priest",
            "npc_dota_neutral_redux_forest_troll_berserker",
            "npc_dota_neutral_redux_dark_troll",
            "npc_dota_wraith_ghost",
            "npc_dota_neutral_redux_ghost",
            "npc_dota_neutral_redux_gnoll_assassin",
            "npc_dota_neutral_redux_small_thunder_lizard",
            "npc_dota_neutral_redux_big_thunder_lizard",
            "npc_dota_neutral_redux_granite_golem",
            "npc_dota_neutral_redux_rock_golem",
            "npc_dota_neutral_redux_prowler_shaman",
            "npc_dota_neutral_redux_prowler_acolyte",
            --"npc_dota_neutral_redux_elder_jungle_stalker",
            --"npc_dota_neutral_redux_jungle_stalker",
            "npc_dota_neutral_redux_giant_wolf",
            "npc_dota_neutral_redux_ogre_magi",
            "npc_dota_neutral_redux_ogre_mauler",
            "npc_dota_neutral_redux_mud_golem",
            "npc_dota_neutral_redux_polar_furbolg_champion",
            "npc_dota_neutral_redux_fel_beast",
            "npc_dota_neutral_redux_centaur_outrunner",
            "npc_dota_neutral_redux_kobold_taskmaster",
            "npc_dota_neutral_redux_kobold_tunneler",
            "npc_dota_neutral_redux_kobold",
        }

		ListenToGameEvent('npc_spawned',function(keys)
			local u = EntIndexToHScript(keys.entindex)
			if u and IsValidEntity(u) then
				if string.find(u:GetUnitName(),"goodguys_ranged") or string.find(u:GetUnitName(),"badguys_ranged") then
					local spawnCount = 0
					while spawnCount < self.minSpawn or self.maxSpawn > spawnCount and RollPercentage(50) do
						spawnCount = spawnCount + 1
						local rnd = RandomInt(1,#self.units)
						local name = self.units[rnd]
						local origin = u:GetAbsOrigin()
						local teamNumber = u:GetTeamNumber()
						local waypoint = u:GetInitialGoalEntity()
						local goal = u:GetInitialGoalPosition()

						-- Freeze and hide them until time reaches .30 or .60
						local waitTime = 30-math.floor(GameRules:GetDOTATime(false,false)%30)
						if waitTime > 28 then
							waitTime = FrameTime()
						end
						local allowed_spawn = true
						Timers:CreateTimer(0.5, function()
							if u and not u:IsNull() then
								-- If the spawned unit is a clone then dont spawn a random lane creep
								allowed_spawn = u:FindAbilityByName("clone_token_ability") == nil
							end
						end)

						Timers:CreateTimer(waitTime+2,function()
							if allowed_spawn then
								local unit = CreateUnitByName(name,origin,true,nil,nil,teamNumber)

								unit:SetInitialGoalEntity(waypoint)
								unit:SetInitialGoalPosition(goal)

								unit:AddNewModifier(unit,nil,"modifier_random_lane_creep_mutator_ai",{})
								unit:AddNewModifier(unit,nil,"modifier_phased",{duration = 2.5})
								ResolveNPCPositions(unit:GetAbsOrigin(),100)
							end
						end)
					end
				end
			end
		end, nil)
	end
end


modifier_random_lane_creep_mutator_ai = class({})
function modifier_random_lane_creep_mutator_ai.IsPermanent(self)
    return true
end
function modifier_random_lane_creep_mutator_ai.IsPurgable(self)
    return false
end
function modifier_random_lane_creep_mutator_ai.IsHidden(self)
    return true
end

function modifier_random_lane_creep_mutator_ai:OnCreated(kv)
    if IsClient() then
        return
    end

    local unit = self:GetParent()
    self.initPos = unit:GetAbsOrigin()

    for i = 0, unit:GetAbilityCount() - 1 do
        local ability = unit:GetAbilityByIndex(i)
        if ability then
            ability:SetLevel(1)
        end
    end
    unit:SetMana(unit:GetMaxMana())
    self:StartIntervalThink(1)
end

function modifier_random_lane_creep_mutator_ai:OnIntervalThink()
	local unit = self:GetParent()
	if not unit or unit:IsNull() then
		self:StartIntervalThink(-1)
		self:Destroy()
		return
	end
	if self:GetElapsedTime() > 30 and ((unit:GetAbsOrigin()-self.initPos):Length2D() < 100) then
		print("modifier_random_lane_creep_mutator_ai: UNIT IS STUCK, didnt move from spawn location")
		unit:ForceKill(false)
		self:StartIntervalThink(-1)
		self:Destroy()
		return
	end

	if not unit:GetInitialGoalEntity() then
		--print("========")
		--print("modifier_random_lane_creep_mutator_ai Initial goal entity: ", unit:GetInitialGoalEntity())
		--print("modifier_random_lane_creep_mutator_ai Initial goal position: ", unit:GetInitialGoalPosition())
		--print("========")
		unit.ordered_to_attack = false
		local units = FindUnitsInRadius(unit:GetTeamNumber(), unit:GetAbsOrigin(), nil, 1800, DOTA_UNIT_TARGET_TEAM_FRIENDLY, DOTA_UNIT_TARGET_BASIC, DOTA_UNIT_TARGET_FLAG_NONE, FIND_ANY_ORDER, false)
		for _, u in pairs(units) do
			if u and IsValidEntity(u) then
				if (string.find(u:GetUnitName(),"goodguys_ranged") or string.find(u:GetUnitName(),"badguys_ranged")) and unit:GetTeamNumber() == u:GetTeamNumber() then
					if u:GetInitialGoalEntity() then
						--unit:SetInitialGoalEntity(u:GetInitialGoalEntity())
						local goal = u:GetInitialGoalEntity():GetAbsOrigin()
						ExecuteOrderFromTable({
							UnitIndex = unit:entindex(),
							OrderType = DOTA_UNIT_ORDER_ATTACK_MOVE,
							Position = goal,
							Queue = true,
						})
						unit.ordered_to_attack = true
						break
					end
				end
			end
		end
		if not unit.ordered_to_attack then
			local buildings = FindUnitsInRadius(unit:GetTeamNumber(), unit:GetAbsOrigin(), nil, FIND_UNITS_EVERYWHERE, DOTA_UNIT_TARGET_TEAM_ENEMY, DOTA_UNIT_TARGET_BUILDING, DOTA_UNIT_TARGET_FLAG_NONE, FIND_CLOSEST, false)
			local closest_building
			for _, building in ipairs(buildings) do
				if building and not building:IsNull() and building:IsAlive() then
					if string.find(building:GetUnitName(), "watch_tower") == nil and string.find(building:GetUnitName(), "lantern") == nil then
						closest_building = building
					end
				end
			end
			if closest_building then
				ExecuteOrderFromTable({
					UnitIndex = unit:entindex(),
					OrderType = DOTA_UNIT_ORDER_ATTACK_MOVE,
					Position = closest_building:GetAbsOrigin(),
					Queue = true,
				})
			end
			unit.ordered_to_attack = true
		end
	--else
		--print("========")
		--print("modifier_random_lane_creep_mutator_ai YEAH, Initial goal entity: ", unit:GetInitialGoalEntity())
		--print("modifier_random_lane_creep_mutator_ai Initial goal position: ", unit:GetInitialGoalPosition())
		--print("========")
	end

	for i = 0, unit:GetAbilityCount() - 1 do
		local ability = unit:GetAbilityByIndex(i)
		if unit:GetCurrentActiveAbility() then return end
		if ability and not ability:IsPassive() and ability:IsCooldownReady() and unit:GetMana() >= ability:GetManaCost(-1) then
			if ability:GetAbilityName() == "dark_troll_warlord_raise_dead" and unit:IsAttacking() then
				ability:CastAbility()
				return
			end

			if ability:GetAbilityName() == "enraged_wildkin_tornado" then
				return
			end
            -- Cast stomps
			if ability:GetCastRange(unit:GetAbsOrigin(),nil) < 50 then
				local units = FindUnitsInRadius(unit:GetTeamNumber(), unit:GetAbsOrigin(), nil, ability:GetSpecialValueFor("radius"), DOTA_UNIT_TARGET_TEAM_ENEMY, DOTA_UNIT_TARGET_HERO, DOTA_UNIT_TARGET_FLAG_NO_INVIS + DOTA_UNIT_TARGET_FLAG_FOW_VISIBLE, FIND_ANY_ORDER, false)
				if #units > 0 then
					ability:CastAbility()
					ability:StartCooldown(ability:GetCooldown(-1))
					unit:SpendMana(ability:GetManaCost(-1),ability)
					--unit:CastAbilityNoTarget(ability,-1)
					return
				end
			end

			local units = FindUnitsInRadius(unit:GetTeamNumber(), unit:GetAbsOrigin(), nil, ability:GetCastRange(unit:GetAbsOrigin(),nil), ability:GetAbilityTargetTeam(), DOTA_UNIT_TARGET_HERO, DOTA_UNIT_TARGET_FLAG_NO_INVIS + DOTA_UNIT_TARGET_FLAG_FOW_VISIBLE, FIND_CLOSEST, false)
			if #units > 0 then
				unit:SetCursorCastTarget(units[1])
				ability:CastAbility()
				ability:StartCooldown(ability:GetCooldown(-1))
				unit:SpendMana(ability:GetManaCost(-1),ability)
				--unit:CastAbilityOnTarget(units[1],ability,-1)
				return
			end
		end
	end
end
