"Abilities" {
    // These are the skill categories
    // The numbers are used for sending skills over the network, as well as encryptions
    "skills" {
        // The main skills, usually always avaiable
        "main" {
            "morph_int_str_redux"                     "1" // custom
            "morph_str_int_redux"                     "1" // custom
            "morph_agi_int_redux"                     "1" // custom
            "morph_int_agi_redux"                      "1" // custom
            "keeper_of_the_light_innate_redux"              "1" // custom
            "night_stalker_innate_redux"                    "1" // custom
            "skywrath_mage_concussive_break"               "1" // custom
            "slark_essence_shift_strength_lod"            "1" // custom
            "slark_essence_shift_intellect_lod"            "1" // custom
            "slark_essence_shift_agility_lod"            "1" // custom
            "ursa_fury_swipes_lod"              "1" // custom
            "ursa_enrage_old"                  "1" // custom
            "pudge_flesh_heap"            "1"
            "silencer_global_break"            "1" // custom
            "silencer_global_disarm"            "1" // custom
            "ogre_magi_multicast_lod"            "1" // custom
            "death_prophet_witchcraft"            "1"
            "earthshaker_aftershock_lod"            "1" // custom

            "abaddon_aphotic_shield"            "1"
            "abaddon_borrowed_time"            "1"
            "abaddon_death_coil"            "1"
            "abaddon_frostmourne"            "1"
            "abyssal_underlord_atrophy_aura"            "1"
            "abyssal_underlord_dark_rift"            "1"
            //"abyssal_underlord_cancel_dark_rift"     "1" // sub-ability of Dark Rift
            "abyssal_underlord_firestorm"            "1"
            "abyssal_underlord_pit_of_malice"            "1"
            "alchemist_acid_spray"            "1"
            "alchemist_chemical_rage"            "1"
            "alchemist_goblins_greed"            "1"
            "alchemist_unstable_concoction"            "1"
            //"alchemist_unstable_concoction_throw"     "1" // sub-ability of Unstable Concoction
            "alchemist_transmuted_scepter"      "1" // custom
            "alchemist_aghnaim_magic_redux"     "1" // custom
            "ancient_apparition_chilling_touch"            "1"
            "ancient_apparition_cold_feet"            "1"
            "ancient_apparition_ice_blast"            "1"
            //"ancient_apparition_ice_blast_release"     "1" // sub-ability of Ice Blast
            "ancient_apparition_ice_vortex"            "1"
            "antimage_blink"            "1"
            "antimage_mana_break"            "1"
            "antimage_mana_void"            "1"
            //"antimage_spell_shield"            "1" // doesn't work
            "antimage_counterspell"        "1"
            "axe_battle_hunger"            "1"
            "axe_berserkers_call"            "1"
            "axe_counter_helix"            "1"
            "axe_culling_blade"            "1"
            "bane_brain_sap"            "1"
            "bane_enfeeble"            "1"
            "bane_fiends_grip"            "1"
            "bane_nightmare"            "1"
            //"bane_nightmare_end"		"1" // sub-ability of Nightmare
            "batrider_firefly"            "1"
            "batrider_flamebreak"            "1"
            "batrider_flaming_lasso"            "1"
            "batrider_sticky_napalm"            "1"
            "beastmaster_call_of_the_wild_boar"            "1"
            "beastmaster_inner_beast"            "1"
            "beastmaster_primal_roar"            "1"
            "beastmaster_wild_axes"            "1"
            "beastmaster_call_of_the_wild_hawk" "1"
            //"beastmaster_hawk_dive"				"1" // crashes the server when used
            //"beastmaster_call_of_the_wild_hawk_attack"    "1" // disappears from skills on game start
            //"beastmaster_hawk_invisibility"               "1" // does not work
            "beastmaster_drums_of_slom"			"1" // works with scepter
            "beastmaster_boar_poison"				"1"
            "bloodseeker_blood_bath"            "1"
            "bloodseeker_bloodrage"            "1"
            "bloodseeker_rupture"            "1"
            "bloodseeker_thirst_lod"            "1" // custom
            "bloodseeker_thirst"            "1"
            "bloodseeker_blood_bath2"           "1" // custom
            "bounty_hunter_jinada"            "1"
            "bounty_hunter_shuriken_toss"            "1"
            "bounty_hunter_track"            "1"
            "bounty_hunter_wind_walk"            "1"
            "brewmaster_drunken_brawler"            "1"
            "brewmaster_drunken_haze"            "1"
            "brewmaster_primal_split"            "1"
            //"brewmaster_primal_split_cancel"		"1" // sub-ability of Primal Split
            "brewmaster_thunder_clap"            "1"
            "brewmaster_cinder_brew"            "1"
            "brewmaster_primal_companion"		"1"
            "bristleback_bristleback"            "1"
            "bristleback_quill_spray"            "1"
            "bristleback_viscous_nasal_goo"            "1"
            "bristleback_warpath"            "1"
            "broodmother_incapacitating_bite"            "1"
            "broodmother_insatiable_hunger"            "1"
            "broodmother_spawn_spiderlings"            "1"
            "broodmother_spin_web"            "1"
            "broodmother_poison_sting"       "1"
            //"broodmother_spawn_spiderite"    "1"
            "centaur_double_edge"            "1"
            "centaur_hoof_stomp"            "1"
            "centaur_return"            "1"
            "centaur_stampede"            "1"
            //"centaur_mount"				"1" // sub-ability of centaur_work_horse
            "chaos_knight_chaos_bolt"            "1"
            "chaos_knight_chaos_strike"            "1"
            "chaos_knight_phantasm"            "1"
            "chaos_knight_reality_rift"            "1"
            "chen_hand_of_god"            "1"
            "chen_holy_persuasion"            "1"
            "chen_penitence"            "1"
            "chen_test_of_faith"            "1"
            //"chen_test_of_faith_teleport"       "1" // does not work
            "chen_divine_favor"                 "1"
            "clinkz_death_pact"            "1"
            "clinkz_searing_arrows"            "1"
            "clinkz_strafe"            "1"
            "clinkz_wind_walk"            "1"
            "clinkz_burning_army"         "1"
			"clinkz_burning_barrage"	"1"
            "crystal_maiden_brilliance_aura"            "1"
            "crystal_maiden_crystal_nova"            "1"
            "crystal_maiden_freezing_field"            "1"
            //"crystal_maiden_freezing_field_stop"		"1" // sub-ability of Freezing Field
            "crystal_maiden_frostbite"            "1"
            "dark_seer_ion_shell"            "1"
            "dark_seer_surge"            "1"
            "dark_seer_vacuum"            "1"
            "dark_seer_wall_of_replica"            "1"
            "dazzle_poison_touch"            "1"
            "dazzle_shadow_wave"            "1"
            "dazzle_shallow_grave"            "1"
            "dazzle_weave"            "1"
            "dazzle_bad_juju" "1"
            "dazzle_bad_juju_redux" "1" // custom
            "dazzle_rain_of_vermin"	"1"
            "death_prophet_carrion_swarm"            "1"
            "death_prophet_exorcism"            "1"
            "death_prophet_silence"            "1"
            "disruptor_glimpse"            "1"
            "disruptor_kinetic_field"            "1"
            "disruptor_static_storm"            "1"
            "disruptor_thunder_strike"            "1"
            "doom_bringer_doom"            "1"
            "doom_bringer_devour_lod"     "1" // custom
            "doom_bringer_scorched_earth"            "1"
            "doom_bringer_infernal_blade"            "1"
            "dragon_knight_breathe_fire"            "1"
            "dragon_knight_dragon_blood"            "1"
            "dragon_knight_dragon_tail"            "1"
            "dragon_knight_elder_dragon_form"            "1"
            //"dragon_knight_frost_breath"          "1" // does not exist
            "drow_ranger_frost_arrows"            "1"
            "drow_ranger_marksmanship"            "1"
            "drow_ranger_wave_of_silence"            "1"
            "drow_splitshot"            "1" // custom
            "drow_ranger_multishot"            "1"
            // "marksmanship_int"                        "1" // custom
            // "marksmanship_str"                        "1" // custom
            "earth_spirit_boulder_smash"            "1"
            "earth_spirit_geomagnetic_grip"            "1"
            "earth_spirit_magnetize"            "1"
            "earth_spirit_rolling_boulder"            "1"
            "earthshaker_echo_slam"            "1"
            "earthshaker_enchant_totem"            "1"
            "earthshaker_fissure"            "1"
            "elder_titan_ancestral_spirit"            "1"
            //"elder_titan_move_spirit"		"1" // sub-ability of Astral Spirit
            //"elder_titan_return_spirit"		"1" // sub-ability of Astral Spirit
            "elder_titan_earth_splitter"            "1"
            "elder_titan_echo_stomp"            "1"             // channels but doesnt stomp if Astral Spirit isnt picked too
            //"elder_titan_echo_stomp_spirit"           "1"         // doesnt work
            "elder_titan_natural_order"            "1"
			//"elder_titan_natural_order_spirit"		"1" // probably only works for the Astral Spirit
            //"ember_spirit_activate_fire_remnant"            "1" // sub-ability of Fire Remnant
            "ember_spirit_fire_remnant"            "1"
            "ember_spirit_flame_guard"            "1"
            "ember_spirit_searing_chains"            "1"
            "ember_spirit_sleight_of_fist"            "1"
            "enchantress_enchant"            "1"
            "enchantress_impetus"            "1"
            "enchantress_natures_attendants"            "1"
            "enchantress_untouchable"            "1"
            "enchantress_bunny_hop"            "1"
			"enchantress_little_friends"	"1"
            "enigma_black_hole"            "1"
            "enigma_demonic_conversion"            "1"
            "enigma_malefice"            "1"
            "enigma_midnight_pulse"            "1"
            "faceless_void_chronosphere"            "1"
            "faceless_void_time_lock"            "1"
            "faceless_void_time_walk"            "1"
            "faceless_void_backtrack"           "1"
            "furion_force_of_nature"            "1"
            "furion_sprout"            "1"
            "furion_teleportation"            "1"
            "furion_wrath_of_nature"            "1"
			"furion_curse_of_the_forest"	"1"
            "gyrocopter_call_down"            "1"
            "gyrocopter_flak_cannon"            "1"
            "gyrocopter_homing_missile"            "1"
            "gyrocopter_rocket_barrage"            "1"
            "side_gunner_redux"                       "1" // custom
            "huskar_berserkers_blood"            "1"
            "huskar_burning_spear"            "1"
            "huskar_inner_vitality"            "1"
            "huskar_life_break"            "1"
            "huskar_berserkers_blood_lod"   "1" // custom
            "huskar_inner_fire"           "1"
            //"invoker_alacrity_lod"            "1"
            //"invoker_chaos_meteor_lod"            "1"
            //"invoker_cold_snap_lod"            "1"
            //"invoker_emp_lod"            "1"
            //"invoker_forge_spirit_lod"            "1"
            //"invoker_ghost_walk_lod"            "1"
            //"invoker_ice_wall_lod"            "1"
            //"invoker_sun_strike_lod"            "1"
            //"invoker_tornado_lod"            "1"
            //"invoker_deafening_blast_lod" "1"
            "invoker_alacrity_ad"            "1"
            "invoker_chaos_meteor_ad"            "1"
            "invoker_cold_snap_ad"            "1"
            "invoker_emp_ad"            "1"
            "invoker_forge_spirit_ad"            "1"
            "invoker_ghost_walk_ad"            "1"
            "invoker_ice_wall_ad"            "1"
            "invoker_sun_strike_ad"            "1"
            "invoker_tornado_ad"            "1"
            "invoker_deafening_blast_ad" "1"
          //  "forged_spirit_melting_strike" "1"      // doesnt work
            "jakiro_dual_breath"            "1"
            "jakiro_ice_path"            "1"
            "jakiro_liquid_fire"            "1"
            "jakiro_macropyre"            "1"
            "juggernaut_blade_dance"            "1"
            "juggernaut_blade_fury"            "1"
            "juggernaut_healing_ward"            "1"
            "juggernaut_omni_slash"            "1"
            "keeper_of_the_light_blinding_light"            "1"
            "keeper_of_the_light_chakra_magic"            "1"
            "keeper_of_the_light_chakra_magic_cooldown"     "1" // custom
            "keeper_of_the_light_illuminate"            "1"
            "keeper_of_the_light_mana_leak"            "1"
            "keeper_of_the_light_recall"            "1"
            "keeper_of_the_light_spirit_form"            "1"
            "keeper_of_the_light_will_o_wisp"   "1"
            "kunkka_ghostship"            "1"
            "kunkka_tidebringer"            "1"
            "kunkka_torrent"            "1"
            "kunkka_torrent_storm"            "1" // needs Torrent
            "kunkka_x_marks_the_spot"            "1"
            "legion_commander_duel"            "1"
            "legion_commander_moment_of_courage"            "1"
            "legion_commander_overwhelming_odds"            "1"
            "legion_commander_press_the_attack"            "1"
            "leshrac_diabolic_edict"            "1"
            "leshrac_lightning_storm"            "1"
            "leshrac_pulse_nova"            "1"
            //"leshrac_pulse_nova_redux"       "1" // not needed for now
            "leshrac_split_earth"            "1"
            "lich_chain_frost"            "1"
            //"lich_dark_ritual"            "1"             // does not exist, removed from the game
            "lich_frost_armor"            "1"
            "lich_frost_nova"            "1"
            "lich_sinister_gaze"          "1"
            "lich_frost_shield"              "1"
            "life_stealer_feast"            "1"
            //"life_stealer_feast_melee"      "1" // TODO: rework into old non-innate Feast
            "life_stealer_infest"            "1"
            //"life_stealer_control"              "1" // sub-ability of Infest
            "life_stealer_open_wounds"            "1"
            "life_stealer_rage"            "1"
            "lina_dragon_slave"            "1"
            "lina_fiery_soul"            "1"
            "lina_laguna_blade"            "1"
            "lina_light_strike_array"            "1"
			"lina_flame_cloak"			"1"
            "lion_finger_of_death"            "1"
            "lion_impale"            "1"
            "lion_mana_drain"            "1"
            "lion_voodoo"            "1"
            "lone_druid_rabid"            "1"
            "lone_druid_spirit_bear"            "1"
            "lone_druid_true_form"            "1"
            "lone_druid_spirit_link" "1"
            "luna_eclipse"            "1"
            "luna_lucent_beam"            "1"
            "luna_lunar_blessing"            "1"
            "luna_moon_glaive"            "1"
            "lycan_feral_impulse"            "1"
            "lycan_howl"            "1"
            "lycan_shapeshift"            "1"
            "lycan_summon_wolves"            "1"
            "lycan_wolf_bite" "1"
            "lycan_summon_wolves_critical_strike"	"1"
            "lycan_summon_wolves_invisibility"		"1"
            "mars_spear"            "1"
            "mars_gods_rebuke" "1"
            "mars_bulwark" "1"
            "mars_arena_of_blood" "1"
            "magnataur_empower"            "1"
            "magnataur_reverse_polarity"            "1"
            "magnataur_shockwave"            "1"
            "magnataur_skewer"            "1"
            "medusa_mana_shield"            "1"
            "medusa_mystic_snake"            "1"
            "medusa_split_shot"            "1"
            "medusa_stone_gaze"            "1"
            "meepo_earthbind"            "1"
            "meepo_geostrike"            "1"
            "meepo_ransack"   		"1"
            "meepo_poof"            "1"
            "mirana_arrow"            "1"
            "mirana_invis"            "1"
            "mirana_leap"            "1"
            "mirana_starfall"            "1"
            "mirana_starfall_lod"            "1" // custom
            "monkey_king_boundless_strike"  "1"
            "monkey_king_tree_dance"  "1"
            "monkey_king_primal_spring"  "1"
            "monkey_king_jingu_mastery"  "1"
            "monkey_king_wukongs_command"   "1"
            //"monkey_king_mischief"  "1" // makes the model of the hero completely invisible sometimes
            "morphling_adaptive_strike_agi"            "1"
            "morphling_adaptive_strike_str"           "1"
            "morphling_morph_agi"            "1"
            "morphling_morph_str"            "1"
            "morphling_replicate"            "1"
            "morphling_waveform"            "1"
            "naga_siren_ensnare"            "1"
            "naga_siren_mirror_image"            "1"
            "naga_siren_rip_tide"            "1"
            "naga_siren_song_of_the_siren"            "1"
            "naga_siren_reel_in"		"1"
            "necrolyte_death_pulse"            "1"
            "necrolyte_sadist_lod"      "1" // custom
            "necrolyte_heartstopper_aura"            "1"
            "necrolyte_reapers_scythe"            "1"
            "necrolyte_sadist"            "1"
            "nevermore_dark_lord"            "1"
            "nevermore_necromastery"            "1"
            "nevermore_requiem"            "1"
            "nevermore_shadowraze1"            "1"
            "nevermore_shadowraze2"            "1"
            "nevermore_shadowraze3"            "1"
            "night_stalker_crippling_fear"            "1"
            "night_stalker_hunter_in_the_night"            "1"
            "night_stalker_void"            "1"
            "night_stalker_darkness"      "1"
            "nyx_assassin_impale"            "1"
            "nyx_assassin_mana_burn"            "1"
            "nyx_assassin_spiked_carapace"            "1"
            "nyx_assassin_vendetta"            "1"
            "nyx_assassin_burrow"            "1"
            "nyx_assassin_burrow_redux"            "1" // custom, Burrow without invis
            "obsidian_destroyer_arcane_orb"            "1"
            "obsidian_destroyer_astral_imprisonment"            "1"
            "obsidian_destroyer_astral_imprisonment_redux" "1" // custom, Old Astral Imprisonment (6.86-7.27d)
            "obsidian_destroyer_essence_aura"	"1"
            "obsidian_destroyer_essence_aura_lod"            "1" // custom, Essence Aura (pre 7.20)
            "obsidian_destroyer_essence_aura_redux"            "1" // custom, Essence Aura (pre 7.20) Redux
            "obsidian_destroyer_sanity_eclipse"            "1"
            "obsidian_destroyer_equilibrium"                "1"
            "ogre_magi_bloodlust"            "1"
            "ogre_magi_fireblast"            "1"
            "ogre_magi_ignite"            "1"
            "omniknight_degen_aura"            "1"
            "omniknight_guardian_angel"            "1"
            "omniknight_purification"            "1"
            "omniknight_repel"            "1"
			"omniknight_martyr"				"1"
            "oracle_false_promise"            "1"
            "oracle_fates_edict"            "1"
            "oracle_fortunes_end"            "1"
            "oracle_purifying_flames"            "1"
            "phantom_assassin_blur"            "1"
            "phantom_assassin_coup_de_grace"            "1"
            "phantom_assassin_phantom_strike"            "1"
            "phantom_assassin_stifling_dagger"            "1"
            "phantom_lancer_doppelwalk"            "1"
            "phantom_lancer_juxtapose"            "1"
            "phantom_lancer_phantom_edge"            "1"
            "phantom_lancer_spirit_lance"            "1"
            "phoenix_fire_spirits"            "1"
            "phoenix_icarus_dive"            "1"
            "phoenix_sun_ray"            "1"
            "phoenix_supernova"            "1"
            "puck_dream_coil"            "1"
            //"puck_ethereal_jaunt"            "1" // sub-ability of Illusory Orb
            "puck_illusory_orb"            "1"
            "puck_phase_shift"            "1"
            "puck_waning_rift"            "1"
            "pudge_dismember"            "1"
            "pudge_meat_hook"            "1"
            "pudge_rot"            "1"
            "pugna_decrepify"            "1"
            "pugna_life_drain"            "1"
            "pugna_nether_blast"            "1"
            "pugna_nether_ward"            "1"
            "queenofpain_blink"            "1"
            "queenofpain_scream_of_pain"            "1"
            "queenofpain_shadow_strike"            "1"
            "queenofpain_sonic_wave"            "1"
            "rattletrap_battery_assault"            "1"
            "rattletrap_hookshot"            "1"
            "rattletrap_power_cogs"            "1"
            "rattletrap_rocket_flare"            "1"
            "rattletrap_overclocking"            "1"
            "razor_eye_of_the_storm"            "1"
            "razor_plasma_field"            "1"
            "razor_static_link"            "1"
            "razor_unstable_current"            "1"
            "riki_blink_strike"            "1"
            "riki_smoke_screen"            "1"
            "riki_backstab_lod"            "1" // custom
            "riki_backstab"            "1"
            "rubick_fade_bolt"            "1"
            "rubick_null_field"            "1"
            "rubick_telekinesis"            "1"
            "rubick_arcane_supremacy"    "1"
            "sandking_burrowstrike"            "1"
            "sandking_epicenter"            "1"
            "sandking_sand_storm"            "1"
            "sandking_caustic_finale"      "1"
            "shadow_demon_disruption"            "1"
            "shadow_demon_shadow_poison"            "1"
            //"shadow_demon_shadow_poison_release"            "1" // sub-ability of Shadow Poison
            "shadow_demon_soul_catcher"            "1"
			"shadow_demon_disseminate"				"1"
            "shadow_shaman_ether_shock"            "1"
            "shadow_shaman_mass_serpent_ward"            "1"
            "shadow_shaman_shackles"            "1"
            "shadow_shaman_voodoo"            "1"
            "shredder_chakram"            "1"
            "shredder_reactive_armor"            "1"
            "shredder_timber_chain"            "1"
            "shredder_whirling_death"            "1"
            "silencer_curse_of_the_silent"            "1"
            "silencer_glaives_of_wisdom"            "1"
            "silencer_global_silence"            "1"
            "silencer_last_word"            "1"
            "skeleton_king_hellfire_blast"            "1"
            "skeleton_king_mortal_strike"            "1"
            "skeleton_king_reincarnation"            "1"
            //"skeleton_king_vampiric_aura"            "1" // does not exist, removed from the game
            "skywrath_mage_ancient_seal"            "1"
            "skywrath_mage_arcane_bolt"            "1"
            "skywrath_mage_concussive_shot"            "1"
            "skywrath_mage_mystic_flare"            "1"
            "slardar_amplify_damage"            "1"
            "slardar_bash"            "1"           //procs on every hit when not skilled, works normally when skilled
            "slardar_slithereen_crush"            "1"
            "slardar_sprint"            "1"
            "slark_dark_pact"            "1"
            "slark_pounce"            "1"
            "slark_essence_shift"            "1"
            "slark_shadow_dance"            "1"
            "sniper_assassinate"            "1"
            "sniper_headshot"            "1"
            "sniper_shrapnel"            "1"
            "sniper_take_aim"            "1"
            "spectre_desolate"            "1"
            "spectre_dispersion"            "1"
            "spectre_haunt"            "1"
            //"spectre_reality"            "1" // sub-ability of Haunt and Shadow Step
            "spectre_haunt_single"            "1"
            "spectre_spectral_dagger"            "1"
            "spirit_breaker_charge_of_darkness"            "1"
            "spirit_breaker_empowering_haste"            "1"
            "spirit_breaker_greater_bash"            "1"
            "spirit_breaker_nether_strike"            "1"
            "spirit_breaker_bulldoze"                 "1"
			"spirit_breaker_planar_pocket"			"1"
            "storm_spirit_ball_lightning"            "1"
            "storm_spirit_electric_vortex"            "1"
            "storm_spirit_overload"            "1"
            "storm_spirit_static_remnant"            "1"
            "sven_gods_strength"            "1"
            "sven_great_cleave"            "1"
            "sven_storm_bolt"            "1"
            "sven_warcry"            "1"
            //"techies_focused_detonate"            "1" // sub-ability of Remote Mines
            "techies_land_mines"            "1"
            "techies_remote_mines"            "1"
            "techies_stasis_trap"            "1"
            "techies_suicide"            "1"
			"techies_minefield_sign"	"1"
            "templar_assassin_meld"            "1"
            "templar_assassin_psi_blades"            "1"
            "templar_assassin_psionic_trap"            "1"
            "templar_assassin_trap_teleport"            "1"
            "templar_assassin_refraction"            "1"
            //"templar_assassin_trap"            "1" // sub-ability of Psionic Trap
            "terrorblade_conjure_image"            "1"
            "terrorblade_metamorphosis"            "1"
            "terrorblade_reflection"            "1"
            "terrorblade_sunder"            "1"
            "tidehunter_anchor_smash"            "1"
            "tidehunter_gush"            "1"
            "tidehunter_kraken_shell"            "1"
            "tidehunter_ravage"            "1"
			"tidehunter_arm_of_the_deep"	"1"
            "tinker_heat_seeking_missile"            "1"
            "tinker_laser"            "1"
            "tinker_march_of_the_machines"            "1"
            "tiny_avalanche"            "1"
            "tiny_craggy_exterior"            "1"
            "tiny_grow"            "1"
            "tiny_grow_lod"            "1" // custom, Grow (pre 7.07)
            "tiny_grow_lod_redux"            "1" // custom, Grow (pre 7.07) Redux
            "tiny_toss"            "1"
            "tiny_tree_channel"     "1"
            "tiny_tree_grab"     "1"
            "treant_eyes_in_the_forest"            "1"
            "treant_leech_seed"            "1"
            "treant_natures_grasp"            "1"
            "treant_living_armor"            "1"
            "treant_natures_guise"            "1"
            "treant_overgrowth"            "1"
            "troll_warlord_battle_trance"            "1"
            "troll_warlord_berserkers_rage"            "1"
            "troll_warlord_fervor"            "1"
            "troll_warlord_whirling_axes_ranged"            "1"
			"troll_warlord_whirling_axes_melee"				"1"
			"troll_warlord_rampage"			"1"
            "tusk_frozen_sigil"            "1"
            "tusk_ice_shards"            "1"
            "tusk_snowball"            "1"
            "tusk_walrus_punch"            "1"
            "tusk_walrus_kick"            "1"
            "tusk_tag_team"               "1"
            "snapfire_scatterblast" "1"
            "snapfire_firesnap_cookie"    "1"
            "snapfire_lil_shredder" "1"
            "snapfire_mortimer_kisses"    "1"
            "void_spirit_aether_remnant"  "1"
            "void_spirit_dissimilate"     "1"
            "void_spirit_resonant_pulse"  "1"
            "void_spirit_astral_step"     "1"
            "undying_decay"            "1"
            "undying_decay_agi"            "1" // custom
            "undying_decay_int"            "1" // custom
            "undying_flesh_golem"            "1"
            "undying_soul_rip"            "1"
            "undying_tombstone"            "1"
			"undying_tombstone_zombie_deathstrike"	"1"
            "ursa_earthshock"            "1"
            "ursa_enrage"            "1"
            "ursa_fury_swipes"              "1"
            "ursa_overpower"            "1"
            "vengefulspirit_command_aura"            "1"
            "vengefulspirit_magic_missile"            "1"
            "vengefulspirit_nether_swap"            "1"
            "vengefulspirit_wave_of_terror"            "1"
            "venomancer_plague_ward"            "1"
            "venomancer_poison_nova"            "1"
            "venomancer_poison_sting"            "1"
            "venomancer_venomous_gale"            "1"
			"venomancer_latent_poison"			"1"
            "viper_corrosive_skin"            "1"
            "viper_nethertoxin"            "1"
            "viper_poison_attack"            "1"
            "viper_viper_strike"            "1"
			"viper_nose_dive"				"1"
            "visage_grave_chill"            "1"
            "visage_soul_assumption"        "1"
            "visage_gravekeepers_cloak"            "1"
            "visage_summon_familiars"            "1"
            "visage_summon_familiars_stone_form"                "1"
            "warlock_fatal_bonds"            "1"
            "warlock_rain_of_chaos"            "1"
            "warlock_shadow_word"            "1"
            "warlock_upheaval"            "1"
            "weaver_geminate_attack"            "1"
            "weaver_shukuchi"            "1"
            "weaver_the_swarm"            "1"
            "weaver_time_lapse"            "1"
            "windrunner_focusfire"            "1"
            "windrunner_powershot"            "1"
            "windrunner_shackleshot"            "1"
            "windrunner_windrun"            "1"
            "wisp_overcharge"            "1"
            "wisp_relocate"            "1"
            "wisp_spirits"            "1"	// crashes server when spirit timer expires
            "wisp_tether"            "1"
            "witch_doctor_death_ward"            "1"
            "witch_doctor_maledict"            "1"
            "witch_doctor_paralyzing_cask"            "1"
            "witch_doctor_voodoo_restoration"            "1"
            "zuus_arc_lightning"            "1"
            "zuus_lightning_bolt"            "1"
            "zuus_static_field"            "1"
            "zuus_thundergods_wrath"            "1"
            "zuus_cloud"                     "1"
            //"life_stealer_consume"            "1" // sub-ability of Infest
            "shadow_demon_demonic_purge"            "1"
            "shredder_chakram_2"            "1"
            "earth_spirit_petrify"            "1"
            //"earth_spirit_stone_caller"            "1" // kinda useless on its own
            "winter_wyvern_arctic_burn"            "1"
            "winter_wyvern_splinter_blast"            "1"
            "winter_wyvern_cold_embrace"            "1"
            "winter_wyvern_winters_curse"            "1"
            "life_stealer_assimilate"            "1"
            //"morphling_hybrid"            "0"               // doesnt work
            "arc_warden_flux"            "1"
            "arc_warden_magnetic_field"            "1"
            "arc_warden_spark_wraith"            "1"
            "arc_warden_tempest_double"            "1"
            "death_prophet_spirit_siphon"            "1"
            "faceless_void_time_dilation"            "1"
            "lone_druid_savage_roar"            "1"
            "riki_tricks_of_the_trade"            "1"
            "lone_druid_true_form_battle_cry"            "1"
            // Brewmaster
            "brewmaster_earth_hurl_boulder"            "1"
            "brewmaster_earth_pulverize"            "1"
			"brewmaster_void_astral_pulse"    "1"
            "brewmaster_storm_wind_walk"            "1"
            "brewmaster_storm_dispel_magic"            "1"
            "brewmaster_fire_permanent_immolation"            "1"
            "brewmaster_storm_cyclone"            "1"
			"brewmaster_fire_phase"				"1"
            // Ogre magi ulty
            "ogre_magi_unrefined_fireblast"            "1"
            // Meepo Ulty
            //"meepo_divided_we_stand"            "1" // moved to single player abilities
            // Rearm
            "tinker_rearm"            "1"
            // Riki
            "riki_permanent_invisibility"            "1"
            // Multicast
            "ogre_magi_multicast"            "1"
            // Aftershock
            "earthshaker_aftershock"            "1"
            "pangolier_swashbuckle" "1"
            "pangolier_shield_crash"      "1"
            //"pangolier_heartpiercer"      "1" // does not work
            "pangolier_gyroshell"   "1"
            "pangolier_lucky_shot"   "1"
            "dark_willow_bramble_maze"    "1"
            "dark_willow_bedlam"    "1"
            "dark_willow_terrorize" "1"
            "dark_willow_shadow_realm"    "1"
            "dark_willow_cursed_crown"    "1"
            "grimstroke_dark_artistry"    "1"
            "grimstroke_ink_creature" "1"
            "grimstroke_spirit_walk"    "1"
            "grimstroke_soul_chain"    "1"
			"grimstroke_dark_portrait" "1"
			"grimstroke_ink_over"	"1"
            //"grimstroke_scepter"    "1" // does not exist, removed from the game
            //"sled_penguin_redux"  "1"	// TODO: Check what this is and maybe fix it
            "hoodwink_acorn_shot"   "1"
            "hoodwink_bushwhack"    "1"
            "hoodwink_scurry"       "1"
            "hoodwink_sharpshooter" "1"
            //"hoodwink_sharpshooter_release"		"1" // sub-ability of Sharpshooter
            "hoodwink_decoy"		"1"
            "hoodwink_hunters_boomerang"	"1"
            "dawnbreaker_fire_wreath" "1"
            "dawnbreaker_celestial_hammer" "1"
            //"dawnbreaker_converge" "1" // sub-ability of Celestial Hammer
            "dawnbreaker_luminosity" "1"
            "dawnbreaker_solar_guardian" "1"
            "life_stealer_ghoul_frenzy" "1"

            // Shard abilities added in 7.27
            "alchemist_berserk_potion"          "1"   // ok
            "antimage_mana_overload"            "1"   // ok
            "bristleback_hairball"              "1"   // needs quills and goo - added warning text
            "broodmother_silken_bola"           "1"   // needs spin web charge - added warning text
            "rattletrap_jetpack"                "1"   // ok
            "dark_seer_normal_punch"            "1"   // ok - added warning text
            "dragon_knight_fireball"            "1"   // ok
            //"faceless_void_time_walk_reverse"   "1"   // sub-ability of Time Walk
            "jakiro_liquid_ice"                 "1"   // misses? (with melee hero), hits but doesnt debuff (with ranged hero)
            "juggernaut_swift_slash"            "1"   // needs omnislash - added warning text
            "kunkka_tidal_wave"                 "1"   // ok
            "leshrac_greater_lightning_storm"   "1"   // ok
            "lich_ice_spire"                    "1"   // ok
            "magnataur_horn_toss"               "1"   // ok
            "medusa_cold_blooded"               "1"   // ok
            "meepo_petrify"                     "1"   // ok
            "necrolyte_death_seeker"            "1"   // needs death pulse - added warning text
            "ogre_magi_smash"                   "1" // fire shield ok
            "omniknight_hammer_of_purity"       "1"   // ok
			"pangolier_rollup"					"1"
            "phantom_assassin_fan_of_knives"    "1"   // ok
            "riki_poison_dart"                  "1"   // ok
            "slark_fish_bait"                   "1"   // ok
            "sniper_concussive_grenade"         "1"   // ok
            "storm_spirit_electric_rave"        "1"   // needs overload - added warning text
            "terrorblade_terror_wave"           "1"   // ok
            "terrorblade_demon_zeal"            "1"   // ok
            "shredder_flamethrower"             "1"   // ok
            "tinker_defense_matrix"             "1"   // ok
            "visage_silent_as_the_grave"        "1"   // ok
            "witch_doctor_voodoo_switcheroo"    "1"   // needs death ward - added warning text

            // Abilities added in 7.3
            "broodmother_sticky_snare"          "1"
            //"abyssal_underlord_dark_portal"     "1" // TODO: needs fixing by adding the sub-ability
            "windrunner_gale_force"             "1"
            "slark_depth_shroud"				"1"   // needs shadow dance - added warning text
			"snapfire_gobble_up"				"1"   // cant get spit creep to work
			// "snapfire_spit_creep"				"1" // sub-ability of Gobble Up
			"keeper_of_the_light_radiant_bind"	"1"

			// Marci
			"marci_grapple"						"1"
			"marci_unleash"						"1"
			"marci_companion_run"				"1"
			"marci_guardian"					"1"

			// 7.31
			"dazzle_good_juju"					"1"
			"oracle_rain_of_destiny"			"1"
			"shadow_demon_demonic_cleanse"		"1"
			"tinker_warp_grenade"				"1"
            // "tinker_shrink_ray"                 "1"	// doesn't work
            "tinker_keen_teleport"			    "1"
            "techies_sticky_bomb"				"1"
			"techies_reactive_tazer"			"1"
            "zuus_heavenly_jump"                "1"

			// Muerta
			"muerta_dead_shot"				"1"
			"muerta_the_calling"			"1"
			"muerta_gunslinger"				"1"
			"muerta_pierce_the_veil"		"1"

            "skywrath_mage_shield_of_the_scion" "1"
            "bloodseeker_blood_mist"            "1"

			// Frostivus - these don't work
			//"frostivus2018_throw_snowball"		"1"
			//"frostivus2018_festive_firework"	"1"
			//"frostivus2018_summon_snowman"		"1"
			//"frostivus2018_decorate_tree"		"1"
			// "seasonal_summon_penguin"			"1"
			// "seasonal_ti9_monkey"				"1"

			// Primal Beast
			"primal_beast_onslaught"			"1"
			"primal_beast_trample"				"1"
			"primal_beast_uproar"				"1"
			"primal_beast_rock_throw"			"1"
			// "primal_beast_onslaught_release"	"1"	// sub-ability of Onslaught
			"primal_beast_pulverize"			"1"

			// UNIMPLEMENTED SKILLS
			"beastmaster_mark_of_the_beast"	"1"
			"crystal_maiden_let_it_go"		"1" // ok
			//"crystal_maiden_ice_rink"		"1" // does not exist, removed from the game
			"furion_greater_sprout"			"1"
			"lich_dark_sorcery"				"1"
			"lich_frost_aura"				"1"
			"lone_druid_entangling_claws"	"1"
			"luna_lunar_grace"				"1"
			"omniknight_angelic_flight"		"1"
			"shadow_shaman_serpentine"		"1"
			"omniknight_pacify"             "1"
			//"muerta_grave_visitation"		"1"  // disappears from skills on game start
			"magnus_strength_of_joelrak"	"1"
			// "centaur_overrun"			"1"  // no effect
			// "roshan_halloween_burn"		"1"  // disappears from skills on game start
			// "magnataur_greater_shockwave"	"1" // disappears
			//"bounty_hunter_lookout"			"1" // summons a bear trap that does nothing
			// "venomancer_area_poison"			"1" // does nothing
			"beastmaster_hawk_perch"        "1" // ok
			"arc_warden_scepter"            "1" // works, summons runes
			//"clinkz_scepter"                "1" // disappears from skills on game start
			//"slardar_scepter"               "1" // disappears from skills on game start

            // 7.33
            "alchemist_corrosive_weaponry"  "1"
            "clinkz_tar_bomb"               "1"
            "drow_ranger_glacier"           "1"
            "meepo_megameepo"               "1"
            "meepo_megameepo_fling"         "1"
            "muerta_parting_shot"           "1"
            "nyx_assassin_jolt"             "1"
            "ogre_magi_dumb_luck"           "1"
            "venomancer_noxious_plague"     "1"
            "zuus_lightning_hands"          "1"

			// 7.35
			"tidehunter_dead_in_the_water"	"1"
			"crystal_maiden_crystal_clone"	"1"
			"brewmaster_void_astral_pull"	"1"
			"antimage_counterspell_ally"    "1"
			"centaur_work_horse"            "1" // added warning text
			"bounty_hunter_wind_walk_ally"  "1"
			//"chen_martyrdom"				"1" // crashes the game when used on self
			"warlock_imp_explode"			"1" // you lose control of your hero
			"warlock_imp_explode_major"		"1" // you lose control of your hero

			// 7.36
			//"abaddon_font_of_avernus"		"1" // does not exist
			//"abaddon_soul_suck"		"1" // does not exist
			"abaddon_the_quickening"		"1"
			"abyssal_underling_archer_aoe"		"1"
			"abyssal_underling_warrior_last_will"		"1"
			"abyssal_underling_warrior_mana_burn"		"1"
			//"abyssal_underlord_abyssal_horde"		"1" // needs a disabled ability to work
			//"alchemist_greevils_greed"		"1" // does not exist
			"ancient_apparition_death_rime"		"1"
			"ancient_apparition_ice_age"		"1"
			"arc_warden_runic_infusion"		"1"
			"arc_warden_tempest_recall"     "1"
			"axe_coat_of_blood"		"1"
			"axe_one_man_army"		"1"
			"bane_ichor_of_nyctasha"		"1"
			"batrider_smoldering_resin"		"1"
			"batrider_stoked"		"1"
			"beastmaster_greater_boar_poison"		"1"
			"bloodseeker_sanguivore"		"1"
			"bounty_hunter_big_game_hunter"		"1"
			"bounty_hunter_cutpurse"		"1"
			//"bounty_hunter_through_and_through_toss"		"1" // does not exist
			"broodmother_spiders_milk"		"1"
			"centaur_horsepower"		"1"
			"centaur_rawhide"		"1"
			//"chaos_knight_innate_spell_refund"		"1" // does not exist
			"chaos_knight_phantasmagoria"		"1"
			"chaos_knight_reins_of_chaos"		"1"
			"chen_innate_check_for_team_change"		"1"
			"chen_summon_convert"		"1"
			"clinkz_bone_and_arrow"		"1"
			"crystal_maiden_blueheart_floe"		"1"
			"dark_seer_heart_of_battle"		"1"
			"dark_seer_mental_fortitude"		"1"
			"dark_seer_quick_wit"		"1"
			"dark_willow_pixie_dust"		"1"
			"dawnbreaker_break_of_dawn"		"1"
			"dawnbreaker_unbreakable"		"1"
			"dazzle_innate_weave"		"1"
			"dazzle_nothl_boon"		"1"
			"death_prophet_innate_healing_mastery"		"1"
			"death_prophet_spirit_collector"		"1"
			"disruptor_electromagnetic_repulsion"		"1"
			"disruptor_innate_kinetic_circle"		"1"
			"disruptor_kinetic_fence"		"1"
			"doom_bringer_devils_bargain"		"1"
			"doom_bringer_lvl_pain"		"1"
			"dragon_knight_inherited_vigor"		"1"
			//"drow_ranger_creep_rally"		"1"  // does not work
			"drow_ranger_silence"		"1"
			"drow_ranger_trueshot"		"1"
			"drow_ranger_vantage_point"		"1"
			//"earth_spirit_stone_remnant"		"1" // does not exist
			//"elder_titan_astral_spirit"		"1" // does not exist
			"elder_titan_momentum"		"1"
			//"enchantress_forest_freebie"		"1" // does not exist
			"enigma_event_horizon"		"1"
			"enigma_gravity_well"		"1"
			"enigma_splitting_image"		"1"
			"faceless_void_distortion_field"		"1"
			"faceless_void_time_zone"		"1"
			"furion_arboreal_might"		"1"
			"furion_fecundity"		"1"
			"furion_hedgerow"		"1"
			"furion_spirit_of_the_forest"		"1"
			"grimstroke_ink_trail"		"1"
			"gyrocopter_chop_shop"		"1"
			"gyrocopter_lock_on"		"1"
			//"hoodwink_go_nutss_boomerang"		"1"  // does not exist
			"hoodwink_mistwoods_wayfarer"		"1"
			"huskar_blood_magic"		"1"
			"invoker_mastermind"		"1"
			"jakiro_double_trouble"		"1"
			//"jakiro_liquid_frost"		"1" // does not exist
			"juggernaut_bladeform"		"1"
			"juggernaut_duelist"		"1"
			"juggernaut_innate_mask_crit_lifesteal"		"1"
			"juggernaut_innate_mask_spin_crit"		"1"
			"keeper_of_the_light_mana_magnifier"		"1"
			//"keeper_of_the_light_solar_bind"		"1" // does not exist
			//"kunkka_ghost_ship_fire_cannons"		"1" // does not exist
			//"kunkka_innate_kunkkas_flask"		"1" // does not exist
			//"kunkka_innate_kunkkas_spyglass"		"1" // does not exist
			"leshrac_chronoptic_nourishment"		"1"
			"leshrac_defilement"		"1"
			"lich_death_charge"		"1"
			"lich_innate_chain_frost_bounces"		"1"
			"lich_innate_chain_frost_projectile_speed"		"1"
			"lich_variant_ice_rite"		"1"
			"life_stealer_corpse_eater"		"1"
			"life_stealer_unfettered"		"1"
			"lina_slow_burn"		"1"
			"lion_to_hell_and_back"		"1"
			//"luna_selemenes_favor"		"1" // does not exist
			"lycan_apex_predator"		"1"
			//"lycan_innate_lone_wolf"		"1" // does not exist
			//"lycan_innate_wolfpack"		"1" // does not exist
			"magnataur_solid_core"		"1"
			"magnus_magnetic_horn"		"1"
			"marci_bodyguard"		"1"
			//"marci_sidekick"		"1" // does not exist
			"marci_special_delivery"		"1"
			//"mars_blood_sport_of_blood"		"1" // does not exist
			"mars_dauntless"		"1"
			"meepo_pack_rat"		"1"
			"meepo_sticky_fingers"		"1"
			//"mirana_moonlight_shadow"		"1" // does not exist
			"mirana_selemenes_faithful"		"1"
			"mirana_solar_flare"		"1"
			"morphling_accumulation"		"1"
			"morphling_ebb"		"1"
			"morphling_flow"		"1"
			"muerta_grave_tracker"		"1"
			"muerta_ofrenda"		"1"
			"muerta_supernatural"		"1"
			"naga_siren_crit"		"1"
			"naga_siren_deluge"		"1"
			"naga_siren_eelskin"		"1"
			"necrolyte_ghost_shroud"		"1"
			"nevermore_frenzy"		"1"
			"night_stalker_heart_of_darkness"		"1"
			"night_stalker_night_reign"		"1"
			"nyx_assassin_innate_mana_burn"		"1"
			"nyx_assassin_nyxth_sense"		"1"
			"obsidian_destroyer_ominous_discernment"		"1"
			"omniknight_healing_hammer"		"1"
			"oracle_clairvoyant_cure"		"1"
			"oracle_clairvoyant_curse"		"1"
			"oracle_prognosticate"		"1"
			"pangolier_fortune_favors_the_bold"		"1"
			"phantom_assassin_immaterial"		"1"
			"phoenix_blinding_sun"		"1"
			"phoenix_dying_light"		"1"
			"primal_beast_colossal"		"1"
			"primal_beast_innate_slow_resistance_per_time"		"1"
			"primal_beast_innate_status_resistance_per_time"		"1"
			"puck_puckish"		"1"
			"pudge_innate_graft_flesh"		"1"
			"pugna_oblivion_savant"		"1"
			"queenofpain_bondage"		"1"
			"queenofpain_masochist"		"1"
			"queenofpain_succubus"		"1"
			"rattletrap_armor_power"		"1"
			"razor_dynamo"		"1"
			"razor_storm_surge"		"1"
			"riki_innate_backstab"		"1"
			"rubick_might_and_magus"		"1"
			"sandking_innate_caustic_impediment"		"1"
			"sandking_innate_caustic_volatility"		"1"
			"sandking_scorpion_strike"		"1"
			"shadow_demon_menace"		"1"
			"shadow_demon_shadow_servant"		"1"
			"shadow_shaman_fowl_play"		"1"
			"shadow_shaman_innate_piglet_pole"		"1"
			"shadow_shaman_innate_snake_jar"		"1"
			"shredder_exposure_therapy"		"1"
			"shredder_twisted_chakram"		"1"
			"silencer_brain_drain"		"1"
			"silencer_irrepressible"		"1"
			"skeleton_king_bone_guard"		"1"
			"skeleton_king_spectral_blade"		"1"
			"skeleton_king_vampiric_spirit"		"1"
			"skywrath_mage_ruin_and_restoration"		"1"
			"skywrath_mage_staff_of_the_scion"		"1"
			"slardar_seaborn_sentinel"		"1"
			"slark_barracuda"		"1"
			"snapfire_buckshot"		"1"
			"sniper_keen_scope"		"1"
			"spectre_spectral"		"1"
			"spirit_breaker_herd_mentality"		"1"
			"spirit_breaker_knockback_amp"		"1"
			"storm_spirit_galvanized"		"1"
			"sven_vanquisher"		"1"
			"sven_wrath_of_god"		"1"
			"techies_spoons_stash"		"1"
			"techies_squees_scope"		"1"
			"terrorblade_dark_unity"		"1"
			"tidehunter_blubber"		"1"
			"tidehunter_krill_eater"		"1"
			"tinker_eureka"		"1"
			"tinker_innate_keen_teleport_gold_on_death"		"1"
			"tinker_innate_keen_teleport_xp_on_death"		"1"
			"tiny_insurmountable"		"1"
			"tiny_rocksteady"		"1"
			"treant_innate_attack_damage"		"1"
			"treant_lifebomb_explode"		"1"
			"troll_warlord_innate_masterful"		"1"
			//"troll_warlord_innate_unflinching"		"1" // does not exist
			"tusk_bitter_chill"		"1"
			"tusk_drinking_buddies"		"1"
			"undying_ceaseless_dirge"		"1"
			"undying_zombie_master"		"1"
			"ursa_bear_down"		"1"
			"ursa_maul"		"1"
			"vengefulspirit_retribution"		"1"
			"vengefulspirit_soul_strike"		"1"
			//"viper_innate_corrosive_skin_vile"		"1" // does not exist
			//"viper_innate_corrosive_skin_virulent"		"1" // does not exist
			"void_spirit_intrinsic_edge"		"1"
			"void_spirit_symmetry"		"1"
			"warlock_black_grimoire"		"1"
			//"warlock_champion_of_gorroth_flaming_fists"		"1" // does not exist
			//"warlock_champion_of_gorroth_permanent_immolation"		"1" // does not exist
			"warlock_eldritch_summoning"		"1"
			"windrunner_easy_breezy"		"1"
			"winter_wyvern_dragon_sight"		"1"
			"winter_wyvern_eldwurm_scholar"		"1"
			"winter_wyvern_essence_of_the_blueheart"		"1"
			"wisp_sight_seer"		"1"
			"witch_doctor_gris_gris"		"1"
			"witch_doctor_innate_maledict_heal_reduction"		"1"

			// 7.37
			"abaddon_withering_mist"		"1"
			"abyssal_underlord_raid_boss"   "1"
			"antimage_persectur"		"1"
			"beastmaster_rugged"		"1"
			"brewmaster_belligerent"		"1"
			"bristleback_prickly"		"1"
			"death_prophet_mourning_ritual"		"1"
			"earthshaker_slugger"           "1"
			"earthshaker_spirit_cairn"		"1"
			"elder_titan_tip_the_scales"		"1"
			"ember_spirit_immolation"		"1"
			"enchantress_rabblerouser"		"1"
			"kunkka_admirals_rum"		"1"
			"legion_commander_outfight_them"		"1"
			"lina_combustion"		"1"
			"lone_druid_bear_necessities"		"1"
			"lone_druid_gift_bearer"		"1"
			"luna_lunar_orbit"		"1"
			"lycan_summon_wolves_bash"		"1"
			"lycan_summon_wolves_hamstring"		"1"
			"lycan_summon_wolves_hightail"		"1"
			"medusa_gorgon_grasp"		"1"
			"medusa_venomed_volley"		"1"
			"phantom_lancer_illusory_armaments"		"1"
			"templar_assassin_third_eye"		"1"
			"troll_warlord_switch_stance"		"1"
			"venomancer_sepsis"		"1"
			"viper_predator"		"1"
			"visage_lurker"		"1"
			"weaver_rewoven"		"1"

			// Ringmaster
			"ringmaster_spotlight"                 "1"
			"ringmaster_tame_the_beasts"           "1"
			"ringmaster_the_box"                   "1"
			"ringmaster_wheel"                     "1"
			"ringmaster_impalement"                "1"
			"ringmaster_dark_carnival_souvenirs"   "1"
        }
        // The neutrals skills
        "neutral" {
            "alpha_wolf_group" {
				"black_dragon_splash_attack"			"1"
                "ghost_frost_attack"					"1"
                "gnoll_assassin_envenomed_weapon"		"1"
                "alpha_wolf_critical_strike"			"1"
				//"giant_wolf_critical_strike"            "1" // inferior version of alpha_wolf_critical_strike
				"berserker_troll_break"					"1"
				"kobold_disarm"							"1"
				"necronomicon_warrior_mana_burn_lod"                "1"
            }

            "big_thunder_lizard_group" {
				"alpha_wolf_command_aura"					"1"
				"centaur_khan_endurance_aura"				"1"
				"big_thunder_lizard_wardrums_aura"			"1"
				"kobold_taskmaster_speed_aura"				"1"
				"black_drake_magic_amplification_aura"		"1"
				"ancient_rock_golem_weakening_aura"			"1"
				"frostbitten_golem_time_warp_aura"			"1" // does not work for the caster/owner
				"hill_troll_rally"							"1"
            }

            "black_dragon_group" {
				"satyr_hellcaller_unholy_aura"				"1"
				"spawnlord_aura"							"1"
				"kobold_tunneler_prospecting"				"1"
				"forest_troll_high_priest_heal_amp_aura"	"1"
				"forest_troll_high_priest_mana_aura"		"1"
				"mudgolem_cloak_aura"						"1"
				"enraged_wildkin_toughness_aura"			"1"
				"black_dragon_dragonhide_aura"				"1"
				"granite_golem_hp_aura"						"1"
				"blue_dragonspawn_overseer_devotion_aura"	"1"
				"necronomicon_archer_aoe_lod"               "1"
				"necronomicon_warrior_sight"				"1"
				"flagbearer_creep_aura_effect"				"1"
				//"mud_golem_rock_destroy"  "1"      // doesnt work
            }

            "blue_dragonspawn_group" {
				"harpy_storm_chain_lightning"               "1"
				"dark_troll_warlord_ensnare"                "1"
                "satyr_soulstealer_mana_burn"               "1"
                "satyr_trickster_purge"                     "1"
                "mud_golem_hurl_boulder"                    "1"
				"warpine_raider_seed_shot"					"1"
				"fel_beast_haunt"							"1"
				"enraged_wildkin_hurricane"					"1"
				"ice_shaman_incendiary_bomb"				"1"
				"necronomicon_archer_mana_burn_lod"         "1"
				"necronomicon_archer_purge"                 "1"
            }

            "centaur_khan_group" {
                "big_thunder_lizard_slam"                 "1"
                "centaur_khan_war_stomp"                  "1"
				"spawnlord_master_stomp"                  "1"
				"polar_furbolg_ursa_warrior_thunder_clap" "1"
            }

            "dark_troll_warlord_group" {
                "enraged_wildkin_tornado"                "1"
                "dark_troll_warlord_raise_dead"          "1"
				"satyr_hellcaller_shockwave"             "1"
				"spawnlord_master_freeze"                "1"
				"black_dragon_fireball"                  "1"
				"giant_wolf_intimidate"					 "1"
				"ogre_bruiser_ogre_smash"				 "1"
				"harpy_scout_take_off"					 "1"
            }

            "enraged_wildkin_group" {
                "ogre_magi_frost_armor"                "1"
                "big_thunder_lizard_frenzy"            "1"
				"forest_troll_high_priest_heal"        "1"
                "blue_dragonspawn_overseer_evasion"		"1"
				"blue_dragonspawn_sorcerer_evasion"		"1"
				"furbolg_enrage_attack_speed"			"1"
				"furbolg_enrage_damage"					"1"
				"necronomicon_warrior_last_will_lod"    "1"
            }

            "lone_druid_spirit_bear_group" {
                "lone_druid_spirit_bear_demolish"                "1"
                "lone_druid_spirit_bear_entangle"                "1"
				"lone_druid_spirit_bear_fetch"					 "1"
                "lone_druid_spirit_bear_return"                "1"
            }

            "satyr_group" {

            }

            "necronomicon_group" {

            }

            "roshan_group" {
                "roshan_slam"                "1"
                "roshan_spell_block"                "1"
                "roshan_bash"                "1"
				"roshan_revengeroar"		"1"
            }

            "prowler_group" {
				"ancient_golem_rockslide"		"1"
				"granite_golem_bash"		"1"
				"spawnlord_master_bash"			"1"
            }

            "warlock_group" {
                "warlock_golem_flaming_fists"                "1"
                "warlock_golem_permanent_immolation"                "1"
                "warlock_golem_permanent_immolation_lod"        "1"
            }

            "misc_neutral_1_group" {

            }

            "misc_neutral_2_group" {

            }
            "misc_neutral_3_group" {

            }
        }
        // The custom skills in LoD
        "custom"
        {
            "flesh_heap"
            {
                  "pudge_flesh_heap_agility"            "1"       // errors on startup but does work ok
                  "pudge_flesh_heap_int"            "1"
                  "pudge_flesh_heap_move_speed"     "1"           // works ok
                  "pudge_flesh_heap_spell_amp"       "1"          // works ok but doesnt show extra spell amp on character sheet
                  "pudge_flesh_heap_attack_range"   "1"           // works ok
                  // "pudge_flesh_heap_attack_speed"   "1"         // script errors
                  "pudge_flesh_heap_cast_range"   "1"             // works ok
                  "pudge_flesh_heap_bonus_vision" "1"             // works ok
                  "pudge_flesh_heap_cooldown_reduction" "1"       // errors on startup but does work ok
                  "pudge_flesh_heap_magic_resistance" "1"         // works ok
                  "pudge_flesh_heap_evasion" "1"                  // errors on startup but does work ok
                  // "pudge_flesh_heap_spell_lifesteal" "1"        // not working
                  // "pudge_flesh_heap_lifesteal" "1"              // not working
                  "pudge_flesh_heap_armor" "1"                    // works ok
                  "pudge_flesh_heap_health_regeneration" "1"      // works ok
                  "pudge_flesh_heap_mana_regeneration" "1"        // works ok
                  "pudge_flesh_heap_minion_damage" "1"            // works ok
                  "pudge_flesh_heap_tenacity" "1"                 // script errors when levelling up but does work ok
                  "pudge_flesh_heap_willpower" "1"                // script errors when levelling up but does work ok

                  // most of these have CalculateStatBonus script errors so may not work as intended

            }

            "survivor"
            {
                  "spell_lab_survivor_health_regen" "1"
                  "spell_lab_survivor_move_speed" "1"
                  "spell_lab_survivor_vision" "1"
                  "spell_lab_survivor_magic_resistance" "1"
            }

            "spell_lab_souls"
            {
                "spell_lab_souls_vision" "1"
                "spell_lab_souls_health_regen" "1"
                "spell_lab_souls_move_speed" "1"
                "spell_lab_souls_magic_resistance" "1"
            }

           "brawler"{
                 "brawler_int"                             "1"
                 "brawler_str"                             "1"
                 "brawler_agi"                             "1"
           }
           "imbaRoshan"{
                  //"imba_roshan_fury"      "1"
                  "imba_tower_healing_hero"     "1"
           }
            "spell_lab" {
                "spell_lab_one_with_nothing" "1"
                "spell_lab_symbiotic" "1"
                "arcane_mastery"   "1"
                "spell_lab_missile_storm" "1"
                "spell_lab_storm_minions" "1"
                "spell_lab_bfg" "1"
                "spell_lab_taxi" "1"
                "spell_lab_ggs" "1"                 //spell effect gets stuck on field - doctors divine shower
                "spell_lab_void_step" "1"
            }
            "oneshotonekill" {
                  "jingtong"  "1"
                  "shiguanghuisu"      "1"
                  "benneng"   "1"
                  "sight"   "1"
                  "zhanhun"   "1"
            }
            "overflow" {
                  "blink_support"  "1"
                  "military"   "1"
                  "spell_reflect"   "1"
                  "berserker" "1"
                  "eldri_anti_magic" "1"
                  "channel_earthquake" "1"
                  "grow_beard" "1"
                  "eat_tree_eldri"  "1"
                  "chi_strike"  "1"
            }
            "angel_arena_blackstar" {
                  "aabs_nightshadow"     "1"
                  "aabs_thunder_musket"   "1"
            }
            "resurgence"{
                  "genos_survival_of_the_fittest"     "1"
            }
            "radiant_jungle"{
                  "spawn_small_camp"            "1"
                  "spawn_medium_camp"           "1"
                  "spawn_large_camp"            "1"
                  "spawn_ancient_camp"          "1"
            }
            "overflow_ult" {
                  "night_wolf" "1"
                  "dark_blade"      "1"
                  "light_blade"   "1"
                  "metamorphosis"   "1"
                  "seer"   "1"                  //vision gets stuck on enemy heroes when used with multicast
                  "spectral_form"   "1"
                  "master_magic"   "1"
            }
            "mercy" {
                  "mercy_caduceus_healing"      "1"
                  //"mercy_caduceus_power"  "1"       //spell works but doesnt give damage or spell bonus
                  "mercy_guardian_angel"  "1"
                  "mercy_angelic_descent" "1"
                  "mercy_heroes_never_die"      "1"
            }

            "holdout" {
                "zuus_thundergods_vengeance"                "1"
                //"holdout_omnislash"                "1"	//disappears when you pick it and start game
                //"holdout_gods_strength"                "1"
                //"holdout_culling_blade"            "1"
                "holdout_arcane_aura"                "1"
                "holdout_gladiators_unite"                "1"
                //"holdout_scourge_ward"          "1"     //error in log: Cannot create an entity because entity class is NULL -1
                //"holdout_multishot"             "1"       //disappears when you pick it and start game
				"mana_laser"					"1"

            }
            "item_abilities" {
                "armoured_centipede"                              "1"
                "aether_range_lod"                "1"
                "octarine_vampirism_lod"                "1"
                "force_dash_lod"                "1"
                "shards_of_truesight_lod"                "1"
            }
           //  "random_abilities" {
           //     "true_random_lod_1"    "1"
           //     "true_random_lod_2"    "1"
           //     "true_random_lod_3"    "1"
           //     "true_random_lod_4"    "1"
           //     "true_random_lod_5"    "1"
           //     "true_random_lod_6"    "1"
           // }
            "cherub_abilities" {
                // "cherub_sleep_cloud"      "1"       //sleep cloud spell effect needs fixing
                "cherub_synthesis"      "1"
                "cherub_explosive_spore"      "1"
                // "cherub_flower_garden"      "1"   // does nothing
            }

            "uther_abiliites"{
                  "uther_Hurl_Hammer"     "1"
                  "uther_Threatening_Bolt"      "1"
                  "uther_omniscience_wave"      "1"
                  "uther_Argent_Smite"      "1"
            }

            "proteus_abiliites"{
                  "proteus_razorwind"     "1"
                  "proteus_polyp"      "1"          // crashed server
                  "proteus_jet"      "1"
                  "proteus_rarefaction"      "1"
            }

            "tenebris_abiliites"{
                  "tenebris_blood_ward"   "1"         // CRASHES
                  //"tenebris_effigy" "1"             // PARTICLES DOES NOT DISSAPEAR
                  "tenebris_fade_strike"  "1"
                  "tenebris_mortal_coil"  "1"
            }

            "suna_abiliites"{
                  "suna_blight_and_wither"      "1"
                  //"suna_dead_mans_chest"  "1"
                  //"suna_kyonshi"    "1"             //sub ability of dead mans chest
                  //"suna_mind_control"     "1"       //SUB-ABILITY
                  "suna_puppeteer"  "1"
                  "suna_vicissitude"      "1"       //not a very good spell
           }

           "veera"{
                  "veera_evasive_roll"    "1"
                  "veera_plains_runner"   "1"
                  "veera_pursuit"   "1"
                  "veera_thrill_of_the_hunt"    "1"
                  "veera_toxic_darts"     "1"
           }

           "zeros"{
                  "zeros_gerrymandering" "1"
                  "zeros_impose_tax" "1"
                  //"zeros_innate" "1"
                  "zeros_royal_statue" "1"
                  "zeros_blade_of_malice" "1"
                  "zeros_fanaticism" "1"
           }

           "achlys"{
                  "achlys_miserable_claws"      "1"
                  "achlys_nights_embrace" "1"
                  "achlys_sorrow_rising"  "1"
                  "achlys_death_mist"     "1"
           }

            "sirocco_abiliites"{
                  "sirocco_shifting_sands"      "1"
                  "sirocco_mirage"  "1"
                  "sirocco_dehydration_aura"    "1"
                  "sirocco_desert_curse"  "1"
            }

            "bellatrix_abiliites"{
                  "bellatrix_blood_cross" "1"
                  "bellatrix_blood_rake"  "1"
                  "bellatrix_live_transfusion"  "1"
                  "bellatrix_unholy_ecstasy"    "1"
            }

            "scaw_abilities"{
                  "scawmar_spirits_away"  "1"       //works ok, complains about texture materials/models/heroes/statuseffects/colorwarp_desat.vtex
                  // "scawmar_fade_blink"    "1"       //simply slower and worse than normal blink or blink dagger etc
                  "scawmar_illusion_line" "1"
                  // "scawmar_mind_control"  "1"       //works, but as bot walked towards my character it crashed dota
                  // "scawmar_scryers_circle"      "1" //works ok, but creates a copy of your hero instead of illusions
            }

            "hylonome_abilities"{
                  "hylonome_eldritch_pull"      "1"
                  "hylonome_battle_rhythm"      "1"
                  "hylonome_anemic_aura"  "1"
                  "hylonome_libation"     "1"
            }

            "keen_abilities"{
                  "keen_commander_mortar_shot"  "1"
                  "keen_commander_recon_systems"      "1"
                  "keen_commander_siege_mode"   "1"
                  "keen_commander_slag_armor"   "1"
            }

            "alexander_abilities"{
                  "alexander_elandras_blessing" "1"
                  "alexander_godfall"     "1"
                  "alexander_radiant"     "1"
                  "alexander_soulseal"    "1"
            }

            "lightning_abilities"{
				  "lightning_lightning_dagger" "1"
                  "lightning_lightning_dagger2" "1"
                  "lightning_overload"    "1"
                  "lightning_spark" "1"
                  "lightning_thunder_wave"     "1"
				  "lightning_blinding_speed"	"1"
				  "lightning_boltblast"		"1"
            }

            "ptomely_abilities"{
                  "ptomely_astralise"     "1"
                  "ptomely_enthrall"      "1"
                  "ptomely_expunge"       "1"
                  "ptomely_mirror_blade"  "1"
            }

            "mifune_abilities"{
                  "mifune_raigeki"  "1"
                  "mifune_genso"    "1"
                  "mifune_oiuchi"   "1"
                  "mifune_zanmato"  "1"
            }

            "erra_abilities"{
                  "erra_deathtouch" "1"
                  "erra_grave_guard"      "1"
                  "erra_morbid_blade"     "1"
                  "erra_to_dust"    "1"
            }

            "lich_abilities"{
                  "lich_absolute_zero" "1"
                  "lich_deep_freeze"  "1"
                  "lich_traveling_frost"  "1"
                  "lich_winters_requiem"  "1"
            }

            "hero_abilities"{
                  //"hero_justice_kick"     "1"       //coding and pushback issues
                  "hero_one_punch"        "1"
                  "hero_freedom_strike"   "1"
                  "hero_heroic_soul"      "1"
            }

            "flower_abilities" {
                "garden_white_flower_base"      "1"
                "garden_red_flower_base"        "1"
                "garden_pink_blossom_base"      "1"
                "garden_blue_blossom_base"      "1"
                "garden_yellow_daisy_base"      "1"
                "garden_purple_lotus_base"      "1"
            }
            "zulf_abilities" {
                //"zulf_cyclone_trap"      "1"  //spell effect needs fixing
                "zulf_jet_stream"      "1"
                //"zulf_gale_force"      "1"    //spell effect needs fixing, does not get removed when spell ends
                "zulf_typhoon"      "1"
            }
            "angel_arena_reborn" {
                "angel_arena_lightning"   "1"
                "angel_arena_magic_fire"      "1"
                "angel_arena_razor_power"     "1"
                "angel_arena_revenge"   "1"         //triggers on neutrals, not on heroes
                "angel_arena_shot"      "1"
                "angel_arena_storm"     "1"
                "angel_arena_summon_hawk"     "1"
                "angel_arena_berserk"   "1"
                "angel_arena_cripple"   "1"
            }
            "angel_arena_reborn_ult" {
                  "angel_arena_darkrage"  "1"
                  //"angel_arena_night_vampire"   "1"       // lifesteal does not work
                  "angel_arena_roots"     "1"
                  "angel_arena_song"      "1"
                  "angel_arena_hola_heal" "1"
                  "angel_arena_transmute" "1"
                  "angel_arena_demonic"   "1"
                  "angel_arena_grace"     "1"
            }
            "angel_arena_tome" {
                  "angel_arena_tome_lvlup"  "1"
                  "angel_arena_tome_gods"  "1"
                  "angel_arena_tome_int"  "1"
                  "angel_arena_tome_str"  "1"
                  "angel_arena_tome_agi"  "1"
                  "angel_arena_tome_med"  "1"
            }

            "life_in_arena" {
                  "ancient_priestess_surge_of_intelligence" "1"
                  "ancient_priestess_spirit_link"     "1"
                  "archmage_magic_barrier"      "1"
                  "berserker_fire_spear"  "1"
                  "dark_ranger_black_arrow"     "1"
                  "firelord_flame_strike" "1"
                  "firelord_fire_trap"    "1"
                  "frost_lord_cold" "1"
                  "frost_lord_frost_breath"     "1"
                  "ghoul_devour"    "1"
                  "akron_explosion" "1"
                  "paladin_blizzard"      "1"
                  "dark_knight_dark_forces"     "1"
                  "lord_of_lightning_lightning_shield"      "1"
                  "android_cluster_rockets"     "1"
                  "serpent_queen_ball_lightning"      "1"
            }
            "life_in_arena_passive" {
                  "butcher_zombie"  "1"
                  "frost_lord_freezing"   "1"
                  "lord_of_lightning_holy_wrath"      "1"
                  "kret_poisoning"  "1"
                  "kret_lust_for_life"    "1"
            }
            "life_in_arena_ferocity" {
                  "brewmaster_ferocity"   "1"               // str version does not increase your health
                  "brewmaster_ferocity_agi"     "1"         // does correctly update your armour
                  "brewmaster_ferocity_int"     "1"         // doesnt change mana pool
                  "brewmaster_ferocity_all"     "1"
            }
            "life_in_arena_ult" {
                  "ancient_priestess_ritual_protection" "1"
                  "berserker_madness"     "1"
                  "frost_lord_ice"  "1"
                  "lord_of_lightning_brain_storm"     "1"
                  "paladin_impregnability"      "1"
                  "angel_arena_archmage_anomaly"      "1"
            }
            "life_in_arena_illusion" {
                  "illusionist_mastery_of_deception"  "1"
                  "illusionist_whiff_of_deception"    "1"
                  "illusionist_agility_paws"    "1"
                  //"illusionist_mastery_of_illusions"  "1"	// creates permament copies of heroes that die and respawn
            }
            "retro_dota" {
                  //"invoker_retro_betrayal"      "1"       // useless ability
                  "invoker_retro_portal"      "1"
                  "invoker_retro_scout"      "1"
                  "invoker_retro_invisibility_aura"      "1"
                  "invoker_retro_confuse"      "1"
                  "invoker_retro_disarm"      "1"
                  "invoker_retro_deafening_blast"      "1"
            }

            "imba_towers_weak" {
                  //"imba_tower_aegis"   "1"            // aura works but doesnt give +3 armour per hero
                  "imba_tower_forest"   "1"
                  "imba_tower_self_repair"   "1"
                  "imba_tower_thorns"   "1"
            }
            "ebf" {
                  "ebf_rubick_arcane_echo" "1"
                  "ebf_mana_fiend_essence_amp"  "1"
                  "ebf_clinkz_trickshot"      "1"
                  "ebf_underlord_expulsion"      "1"
                  "ebf_troll_warlord_multistrike"      "1"
            }
            "dusk" {
                  "gemini_abyssal_vortex" "1"
                  "gemini_unstable_rift"  "1"
                  "gemini_voidal_flare" "1"
                  "gemini_extraplanar_pact" "1"
            }
            "duskMisc1" {
                  "self_explosion" "1"
                  //"ancient_defensive_wave"      "1"       //lua code needs fixing
                  //"ancient_last_resort"   "1"             //Its bugged with illusions, it brings them back to life
                  //"paragon_tranquility_seal"    "1"       //spell doesnt prevent damage and cant be cast on buildings
            }
            "duskMisc2" {
                  "crimson_blood_sorcery" "1"
                  "alchemist_alchemise"   "1"
                  "alchemist_motherloads" "1"
                  "aether_reality_shift"  "1"
            }

            "lysander" {
                  //"lysander_adventurous_gale"   "1"       //crashes dota when used
                  "lysander_captains_compass"   "1"
                  "lysander_grapeshot"    "1"
                  "lysander_phantom_fleet"      "1"
            }
            "basic_abilities"
            {
                  "basic_tenacity_bonus" "1"
                  //"basic_willpower_bonus" "1"
                  "basic_mana_bonus" "1"
                  "basic_health_bonus" "1"
                  "basic_gpm_bonus" "1"
                  "basic_movespeed_bonus" "1"
                  "basic_xpm_bonus" "1"
                  "basic_spell_amp_bonus" "1"
                  "basic_stat_gain_bonus" "1"
                  "basic_stat_bonus" "1"
                  "ability_mjolnir" "1"
                  "ability_blademail" "1"
                  "ability_wards"   "1"
                  "bash_reflect" "1"
                  // "basic_bat" "0"
                  // "basic_bat_reduction" "0" // stops game working correctly
            }


            "hawkeye" {
                  "hawkeye_detonator_dart" "1"
                  //"hawkeye_double_tap"  "1"     //single tap fires ok, second spell moves abilities around and doesnt work
                  "hawkeye_hit_n_run" "1"
                  "hawkeye_ricochet" "1"
            }
            "molten" {
                  "bulwark_strike"  "1"
                  "skipping_flames"       "1"
                  "unwavering_stance"     "1"
                  "molten_charge"    "1"
            }

            "DoD" {
                  "makemeleecreeps_lua"   "1"
                  "makerangedcreeps_lua"   "1"
                  "makecatapults_lua"   "1"
            }
            "memes_reborn"{
                  "lina_banana_redux"     "1"
                  "lina_coconut_redux"    "1"
                  "lina_grapefruit_redux" "1"
            }
            "patron_abilities" {
                  "crater" "1"
                  //"ranged_punch" "1"                      //crashes tools mode, no spell effect in normal game
                  "pushing_blast" "1"
				//"lone_druid_spirit_bear_return_lod"   "1" // TODO: Rewrite to be the old behaviour
            }

        }
        "imba"
        {
            // "hero_shredder"
            // {
            //     "imba_shredder_timber_chain"  "1"
            //     "imba_shredder_chakram"  "1"
            //     "imba_shredder_whirling_death"  "1"
            //     "imba_shredder_return_chakram"  "1"
            //     "imba_shredder_dendrophobia"  "1"
            //     "imba_shredder_reactive_armor"  "1"
            // }
            //"hero_naga_siren"
            //{
            //    "imba_naga_siren_rip_tide"  "1"
            //    "imba_naga_siren_mirror_image"  "1"
            //}
            //"hero_beastmaster"
            //{
            //    "imba_beastmaster_summon_boar"  "1"
            //    "imba_beastmaster_hawk_invis"  "1"
            //    "imba_beastmaster_summon_hawk"  "1"
            //    "imba_beastmaster_boar_poison"  "1"
            //}
            //"hero_shadow_shaman"
            //{
            //    "imba_shadow_shaman_mass_serpent_ward"  "1"
            //}
            //"hero_hell_empress"
            //{
            //   "imba_empress_hurl_through_hell"  "1"
            //    "imba_empress_ambient_effects"  "1"
            //    "imba_empress_royal_wrath"  "1"
            //    "imba_empress_hellbolt"  "1"
            //    "imba_empress_eleven_curses"  "1"
            //}
            //"hero_chaos_knight"
            //{
            //    "imba_chaos_knight_phantasm"  "1"
            //    "imba_chaos_knight_reality_rift"  "1"
            //}
            //"hero_sly_king"
            //{
            //    "imba_sly_king_winterbringer"  "1"
            //    "imba_sly_king_frozen_skin"  "1"
            //    "imba_sly_king_burrow_blast"  "1"
            //    "imba_sly_king_frost_gale"  "1"
            //}
            //"hero_tinker"
            //{
            //    "imba_tinker_march_of_the_machines"  "1"
            //    "imba_tinker_laser"  "1"
            //    "imba_tinker_rearm"  "1"
            //    "imba_tinker_heat_seeking_missile"  "1"
            //    "imba_tinker_technomancy"  "1"
            //}
            //"hero_doom_bringer"
            //{
            //    "imba_doom_bringer_doom"  "1"
            //}
            //"hero_phantom_lancer"
            //{
            //    "imba_phantom_lancer_spirit_lance"  "1"
            //}
            //"hero_techies"
            //{
            //    "imba_techies_remote_mine_pinpoint_detonation"  "1"
            //    "imba_techies_focused_detonate"  "1"
            //    "imba_techies_stasis_trap"  "1"
            //    "imba_techies_remote_mine"  "1"
            //    "imba_techies_stasis_trap_trigger"  "1"
            //    "imba_techies_minefield_sign"  "1"
            //    "imba_techies_proximity_mine_trigger"  "1"
            //    "imba_techies_blast_off"  "1"
            //}
            //"hero_rubick"
            //{
            //    "imba_rubick_spell_steal_controller"  "1"
            //    "imba_rubick_telekinesis"  "1"
            //}
            //"hero_spectre"
            //{
            //    "imba_spectre_reality"  "1"
            //    "imba_spectre_haunt"  "1"
            //}
            "hero_abaddon"
            {
                "imba_abaddon_aphotic_shield"  "1"
                "imba_abaddon_curse_of_avernus"  "1"
                "imba_abaddon_mist_coil"  "1"
                //"imba_abaddon_over_channel"  "1"          // HIDDEN ABILITY - DO NOT RE-ENABLE
                "imba_abaddon_borrowed_time"  "1"
            }
            "hero_alchemist"
            {
                "imba_alchemist_mammonite"  "1"
                "imba_alchemist_goblins_greed"  "1"
                "imba_alchemist_acid_spray"  "1"
                "imba_alchemist_chemical_rage"  "1"
                //"imba_alchemist_greevils_greed"  "1"
                "imba_alchemist_unstable_concoction"  "1"
            }
            "hero_antimage"
            {
                "imba_antimage_spell_shield"  "1"
                "imba_antimage_mana_void"  "1"
                "imba_antimage_mana_break"  "1"
                "imba_antimage_blink"  "1"
            }
            "hero_axe"
            {
                "imba_axe_berserkers_call"  "1"
                "imba_axe_culling_blade"  "1"
                "imba_axe_battle_hunger"  "1"
                "imba_axe_counter_helix"  "1"
            }
            "hero_bane"
            {
                "imba_bane_enfeeble"  "1"
                "imba_bane_brain_sap"  "1"
                "imba_bane_fiends_grip"  "1"
                //"imba_bane_nightmare_end"  "1"            // HIDDEN ABILITY
                "imba_bane_nightmare"  "1"
            }
            "hero_bloodseeker"
            {
                "imba_bloodseeker_blood_bath"  "1"
                "imba_bloodseeker_thirst"  "1"
                "imba_bloodseeker_bloodrage"  "1"
                "imba_bloodseeker_rupture"  "1"
            }
            "hero_bounty_hunter"
            {
                "imba_bounty_hunter_shadow_walk"  "1"
                "imba_bounty_hunter_jinada"  "1"
                "imba_bounty_hunter_shuriken_toss"  "1"
                "imba_bounty_hunter_headhunter"  "1"
                "imba_bounty_hunter_track"  "1"
            }
            "hero_bristleback"
            {
                "imba_bristleback_viscous_nasal_goo"  "1"
                "imba_bristleback_quill_spray"  "1"
                "imba_bristleback_bristleback"  "1"
                "imba_bristleback_warpath"  "1"
            }
            "hero_centaur"
            {
                "imba_centaur_hoof_stomp"  "1"
                "imba_centaur_double_edge"  "1"
                "imba_centaur_return"  "1"
                "imba_centaur_thick_hide"  "1"
                "imba_centaur_stampede"  "1"
            }
            "hero_chen"
            {
                "imba_chen_test_of_faith"  "1"
                "imba_chen_divine_favor"  "1"
                "imba_chen_holy_persuasion"  "1"
                "imba_chen_hand_of_god"  "1"
            }
            "hero_clinkz"
            {
                "imba_clinkz_searing_arrows"  "1"
                //"imba_clinkz_death_pact"  "1"             //doesnt show up in search
                "imba_clinkz_skeleton_walk"  "1"
                "imba_clinkz_strafe"  "1"
            }
            "hero_rattletrap"
            {
                "imba_rattletrap_battery_assault"  "1"
                "imba_rattletrap_power_cogs"  "1"
                "imba_rattletrap_rocket_flare"  "1"
                "imba_rattletrap_hookshot"  "1"
            }
            "hero_crystal_maiden"
            {
                "imba_crystal_maiden_crystal_nova"  "1"
                "imba_crystal_maiden_arcane_dynamo"  "1"
                "imba_crystal_maiden_freezing_field"  "1"
                "imba_crystal_maiden_brilliance_aura"  "1"
                "imba_crystal_maiden_frostbite"  "1"
            }
            "hero_dark_seer"
            {
                "imba_dark_seer_vacuum"  "1"
                "imba_dark_seer_ion_shell"  "1"
                "imba_dark_seer_surge"  "1"
                //"imba_dark_seer_wormhole"  "1"            //doesnt show up, related to vacuum ability, extra part of the spell
                "imba_dark_seer_wall_of_replica"  "1"
            }
            "hero_dazzle"
            {
                "imba_dazzle_ressurection"  "1"
                "imba_dazzle_shadow_wave"  "1"
                "imba_dazzle_poison_touch"  "1"
                "imba_dazzle_shallow_grave"  "1"
                "imba_dazzle_bad_juju"  "1"
            }
            "hero_magnataur"
            {
                "imba_magnataur_skewer"  "1"
                "imba_magnataur_shockwave"  "1"
                "imba_magnataur_empower"  "1"
                "imba_magnataur_reverse_polarity"  "1"
            }
            "hero_disruptor"
            {
                "imba_disruptor_static_storm"  "1"
                "imba_disruptor_glimpse"  "1"
                "imba_disruptor_kinetic_field"  "1"
                "imba_disruptor_stormbearer"  "1"
                "imba_disruptor_thunder_strike"  "1"
            }
            "hero_dragon_knight"
            {
                "imba_dragon_knight_dragon_blood"  "1"
                "imba_dragon_knight_elder_dragon_charge"  "1"
                "imba_dragon_knight_elder_dragon_form"  "1"
                "imba_dragon_knight_dragon_tail"  "1"
                "imba_dragon_knight_breathe_fire"  "1"
            }
            "hero_drow_ranger"
            {
                "imba_drow_ranger_deadeye"  "1"
                "imba_drow_ranger_marksmanship"  "1"
                "imba_drow_ranger_frost_arrows"  "1"
                "imba_drow_ranger_gust"  "1"
                "imba_drow_ranger_trueshot"  "1"
            }
            "hero_earth_spirit"
            {
                "imba_earth_spirit_boulder_smash"  "1"
                "imba_earth_spirit_rolling_boulder"  "1"
                "imba_earth_spirit_geomagnetic_grip"  "1"
                "imba_earth_spirit_stone_remnant"  "1"
                "imba_earth_spirit_petrify"  "1"
                "imba_earth_spirit_magnetize"  "1"
            }
            "hero_elder_titan"
            {
                "imba_elder_titan_echo_stomp"  "1"
                //"imba_elder_titan_echo_stomp_spirit"  "1"       // doesnt work
                "imba_elder_titan_ancestral_spirit"  "1"
                //"imba_elder_titan_return_spirit"  "1"
                "imba_elder_titan_natural_order"  "1"
                "imba_elder_titan_earth_splitter"  "1"
            }
            "hero_ember_spirit"
            {
                "imba_ember_spirit_searing_chains"  "1"
                "imba_ember_spirit_sleight_of_fist"  "1"
                "imba_ember_spirit_flame_guard"  "1"
                "imba_ember_spirit_activate_fire_remnant"  "1"
                "imba_ember_spirit_fire_remnant"  "1"
            }
            "hero_enchantress"
            {
                "imba_enchantress_untouchable"  "1"
                "imba_enchantress_enchant"  "1"
                "imba_enchantress_natures_attendants"  "1"
                "imba_enchantress_natura_shift"  "1"
                "imba_enchantress_impetus"  "1"
            }
            "hero_enigma"
            {
                "imba_enigma_malefice"  "1"
                "imba_enigma_demonic_conversion"  "1"
                "imba_enigma_midnight_pulse"  "1"
                "imba_enigma_black_hole"  "1"
            }
            "hero_faceless_void"
            {
                "imba_faceless_void_time_walk"  "1"
                "imba_faceless_void_time_dilation"  "1"
                "imba_faceless_void_time_lock"  "1"
				"imba_faceless_void_time_lock_720" "1"
                "imba_faceless_void_timelord"  "1"
                "imba_faceless_void_chronosphere"  "1"
            }
            "hero_huskar"
            {
                //"imba_huskar_inner_vitality"  "1"   // cant skill up
                "imba_huskar_inner_fire"  "1"
                "imba_huskar_burning_spear"  "1"
                "imba_huskar_berserkers_blood"  "1"
                "imba_huskar_life_break"  "1"
            }
            "hero_jakiro"
            {
                //"imba_jakiro_ice_breath"  "1"       // linked to fire breath
                "imba_jakiro_fire_breath"  "1"
                "imba_jakiro_liquid_fire"  "1"
                "imba_jakiro_ice_path"  "1"
                "imba_jakiro_macropyre"  "1"
            }
            "hero_juggernaut"
            {
                "imba_juggernaut_healing_ward"  "1"
                //"imba_juggernaut_healing_ward_passive"  "1"
                "imba_juggernaut_blade_dance"  "1"
                "imba_juggernaut_blade_fury"  "1"
                "imba_juggernaut_omni_slash"  "1"
            }
            "hero_keeper_of_the_light"
            {
                "imba_keeper_of_the_light_illuminate"  "1"
                "imba_keeper_of_the_light_blinding_light"  "1"
                "imba_keeper_of_the_light_chakra_magic"  "1"
                "imba_keeper_of_the_light_spotlights"  "1"
                "imba_keeper_of_the_light_will_o_wisp"  "1"
            }
            "hero_kunkka"
            {
                "imba_kunkka_torrent"  "1"
                "imba_kunkka_tidebringer"  "1"
                "imba_kunkka_x_marks_the_spot"  "1"
                "imba_kunkka_return"  "1"
                "imba_kunkka_ebb_and_flow"  "1"
                "imba_kunkka_ghostship"  "1"
            }
            "hero_lich"
            {
                "imba_lich_frost_nova"  "1"
                //"imba_lich_frost_armor"  "1"
                "imba_lich_frost_shield"  "1"
                "imba_lich_sinister_gaze"  "1"
                "imba_lich_dark_ritual"  "1"
                "imba_lich_cold_front"  "1"
                "imba_lich_chain_frost"  "1"
            }
            "hero_lina"
            {
                "imba_lina_dragon_slave"  "1"
                "imba_lina_light_strike_array"  "1"
                "imba_lina_fiery_soul"  "1"
                "imba_lina_laguna_blade"  "1"
            }
            "hero_lion"
            {
                "imba_lion_mana_drain"  "1"
                "imba_lion_hex"  "1"
                "imba_lion_earth_spike"  "1"
                "imba_lion_finger_of_death"  "1"
            }
            "hero_luna"
            {
                "imba_luna_lucent_beam"  "1"
                "imba_luna_moon_glaive"  "1"
                "imba_luna_lunar_blessing"  "1"
                "imba_luna_eclipse"  "1"
            }
            "hero_lycan"
            {
                //"imba_lycan_summon_wolves"  "1"
                "imba_lycan_howl"  "1"
                "imba_lycan_feral_impulse"  "1"
                "imba_lycan_wolfsbane"  "1"
                "imba_lycan_shapeshift"  "1"

                "imba_summoned_wolf_wicked_crunch"  "1"
                //"imba_summoned_wolf_hunter_instincts"  "1"
                //"imba_summoned_wolf_invisibility"  "1"
            }
            "hero_medusa"
            {
                "imba_medusa_split_shot"  "1"
                "imba_medusa_mystic_snake"  "1"
                "imba_medusa_mana_shield"  "1"
                "imba_medusa_stone_gaze"  "1"
            }
            "hero_mirana"
            {
                "imba_mirana_starfall"  "1"
                "imba_mirana_moonlight_shadow"  "1"
                "imba_mirana_arrow"  "1"
                "imba_mirana_leap"  "1"
            }
            "hero_necrolyte"
            {
                "imba_necrolyte_death_pulse"  "1"
                "imba_necrolyte_ghost_shroud"  "1"
                "imba_necrolyte_heartstopper_aura"  "1"
                "imba_necrolyte_sadist"  "1"
                "imba_necrolyte_reapers_scythe"  "1"
            }
            "hero_night_stalker"
            {
                "imba_night_stalker_void"  "1"
                "imba_night_stalker_crippling_fear_720"  "1"
                "imba_night_stalker_hunter_in_the_night"  "1"
                "imba_night_stalker_stalker_in_the_night"  "1"
                "imba_night_stalker_darkness"  "1"
            }
            "hero_nyx_assassin"
            {
                "imba_nyx_assassin_spiked_carapace"  "1"
                "imba_nyx_assassin_mana_burn"  "1"
                "imba_nyx_assassin_impale"  "1"
                "imba_nyx_assassin_vendetta"  "1"
            }
            "hero_obsidian_destroyer"
            {
                "imba_obsidian_destroyer_arcane_orb"  "1"
                "imba_obsidian_destroyer_astral_imprisonment"  "1"
                "imba_obsidian_destroyer_equilibrium"  "1"
                "imba_obsidian_destroyer_sanity_eclipse"  "1"
            }
            "hero_omniknight"
            {
                "imba_omniknight_purification"  "1"
                "imba_omniknight_repel"  "1"
                "imba_omniknight_hammer_of_virtue"  "1"
                "imba_omniknight_guardian_angel"  "1"
            }
            "hero_pangolier"
            {
                "imba_pangolier_swashbuckle"  "1"
                "imba_pangolier_shield_crash"  "1"
                "imba_pangolier_heartpiercer"  "1"
                "imba_pangolier_lucky_shot"  "1"
                "imba_pangolier_gyroshell"  "1"
            }
            "hero_phantom_assassin"
            {
                "imba_phantom_assassin_stifling_dagger"  "1"
                "imba_phantom_assassin_phantom_strike"  "1"
                "imba_phantom_assassin_blur"  "1"
                "imba_phantom_assassin_coup_de_grace"  "1"
            }
            "hero_phoenix"
            {
                "imba_phoenix_icarus_dive"  "1"
                // "imba_phoenix_icarus_dive_stop"  "1"
                "imba_phoenix_fire_spirits"  "1"
                //"imba_phoenix_launch_fire_spirit"  "1"
                "imba_phoenix_sun_ray"  "1"
                // "imba_phoenix_sun_ray_toggle_move"  "1"
                // "imba_phoenix_sun_ray_stop"  "1"
                "imba_phoenix_burning_wings"  "1"
                "imba_phoenix_supernova"  "1"
            }
            "hero_pudge"
            {
                "imba_pudge_meat_hook"  "1"
                "imba_pudge_sharp_hook"  "1"
                "imba_pudge_light_hook"  "1"
                "imba_pudge_rot"  "1"
                "imba_pudge_flesh_heap"  "1"
                "imba_pudge_dismember"  "1"
            }
            "hero_pugna"
            {
                "imba_pugna_nether_blast"  "1"
                "imba_pugna_decrepify"  "1"
                //"imba_pugna_nether_ward"  "1"       //broken
                //"imba_pugna_nether_ward_aura"  "1"
                "imba_pugna_life_drain"  "1"
                //"imba_pugna_life_drain_end"  "1"
            }
            "hero_queenofpain"
            {
                "imba_queenofpain_shadow_strike"  "1"
                "imba_queenofpain_blink"  "1"
                "imba_queenofpain_scream_of_pain"  "1"
                "imba_queenofpain_sonic_wave"  "1"
                "imba_queenofpain_delightful_torment"  "1"
            }
            "hero_riki"
            {
                "imba_riki_smoke_screen"  "1"
                "imba_riki_blink_strike"  "1"
                "imba_riki_cloak_and_dagger"  "1"
                "imba_riki_tricks_of_the_trade"  "1"
            }
            "hero_sand_king"
            {
                "imba_sandking_epicenter"  "1"
                //"imba_sandking_sand_storm"  "1"     //Duplicate
                "imba_sandking_sand_storm_720"  "1"
                "imba_sandking_caustic_finale"  "1"
                "imba_sandking_burrowstrike"  "1"
            }
            "hero_nevermore"
            {
                "imba_nevermore_necromastery"  "1"
                "imba_nevermore_shadowraze_close"  "1"
                "imba_nevermore_dark_lord"  "1"
                "imba_nevermore_requiem"  "1"
                "imba_nevermore_shadowraze_far"  "1"
                "imba_nevermore_shadowraze_medium"  "1"
            }
            "hero_silencer"
            {
                "imba_silencer_arcane_curse"  "1"
                "imba_silencer_glaives_of_wisdom"  "1"
                "imba_silencer_last_word"  "1"
                "imba_silencer_arcane_supremacy"  "1"
                "imba_silencer_global_silence"  "1"
            }
            "hero_skywrath_mage"
            {
                "imba_skywrath_mage_arcane_bolt"  "1"
                "imba_skywrath_mage_concussive_shot"  "1"
                "imba_skywrath_mage_ancient_seal"  "1"
                "imba_skywrath_mage_mystic_flare"  "1"
            }
            "hero_slardar"
            {
                "imba_slardar_corrosive_haze"  "1"
                "imba_slardar_slithereen_crush"  "1"
                "imba_slardar_bash_of_the_deep"  "1"      //error when not skilled, works when skilled - The chance was not found! Make sure to add it to the table or change the value.
                "imba_slardar_guardian_sprint"  "1"
                "imba_slardar_rain_cloud"  "1"
            }
            "hero_sniper"
            {
                "imba_sniper_shrapnel"  "1"
                "imba_sniper_headshot"  "1"
                "imba_sniper_take_aim"  "1"
                "imba_sniper_assassinate"  "1"
            }
            "hero_spirit_breaker"
            {
                "imba_spirit_breaker_charge_of_darkness"  "1"
                "imba_spirit_breaker_bulldoze"  "1"
                "imba_spirit_breaker_greater_bash"  "1"
                "imba_spirit_breaker_nether_strike"  "1"
            }
            "hero_storm_spirit"
            {
                "imba_storm_spirit_overload"  "1"
                "imba_storm_spirit_static_remnant"  "1"
                "imba_storm_spirit_electric_vortex"  "1"
                "imba_storm_spirit_ball_lightning"  "1"
            }
            "hero_sven"
            {
                "imba_sven_warcry"  "1"
                "imba_sven_colossal_slash"  "1"
                "imba_sven_great_cleave"  "1"
                "imba_sven_storm_bolt"  "1"
                "imba_sven_gods_strength"  "1"
            }
            "hero_tidehunter"
            {
                "imba_tidehunter_gush"  "1"
                "imba_tidehunter_kraken_shell"  "1"
                "imba_tidehunter_anchor_smash"  "1"
                "imba_tidehunter_ravage"  "1"
            }
            "hero_tiny"
            {
                "imba_tiny_rolling_stone"  "1"
                "imba_tiny_avalanche"  "1"
                "imba_tiny_toss"  "1"
                "imba_tiny_craggy_exterior"  "1"
                "imba_tiny_tree_grab"  "1"
                "imba_tiny_tree_throw"  "1"
                "imba_tiny_grow"  "1"
            }
            "hero_troll_warlord"
            {
                "imba_troll_warlord_berserkers_rage"  "1"
                "imba_troll_warlord_whirling_axes_ranged"  "1"
                "imba_troll_warlord_whirling_axes_melee"  "1"
                "imba_troll_warlord_fervor"  "1"
                "imba_troll_warlord_battle_trance"  "1"
            }
            "hero_ursa"
            {
                "imba_ursa_territorial_hunter"  "1"
                "imba_ursa_earthshock"  "1"
                "imba_ursa_enrage"  "1"
                "imba_ursa_fury_swipes"  "1"
                "imba_ursa_overpower"  "1"
            }
            "hero_vengefulspirit"
            {
                "imba_vengefulspirit_magic_missile"  "1"
                "imba_vengefulspirit_wave_of_terror"  "1"
                "imba_vengefulspirit_command_aura"  "1"
                "imba_vengefulspirit_rancor"  "1"
                "imba_vengefulspirit_nether_swap"  "1"
                //"imba_vengefulspirit_swap_back"  "1"
            }
            "hero_venomancer"
            {
                "imba_venomancer_venomous_gale"  "1"
                "imba_venomancer_plague_ward"  "1"
                "imba_venomancer_poison_sting"  "1"
                "imba_venomancer_poison_nova"  "1"
                "imba_venomancer_toxicity"  "1"
            }
            "hero_warlock"
            {
                "imba_warlock_fatal_bonds"  "1"
                "imba_warlock_shadow_word"  "1"
                "imba_warlock_upheaval"  "1"
                "imba_warlock_rain_of_chaos"  "1"
                "imba_warlock_flaming_fists"  "1"
                //"imba_warlock_golem_spell_immunity"  "1"
                "imba_warlock_permanent_immolation"  "1"
            }
            "hero_winter_wyvern"
            {
                "imba_winter_wyvern_arctic_burn"  "1"
                "imba_winter_wyvern_splinter_blast"  "1"
                "imba_winter_wyvern_cold_embrace"  "1"
                "imba_winter_wyvern_winters_curse"  "1"
            }
            "hero_wisp"
            {
                "imba_wisp_tether"  "1"
                "imba_wisp_spirits"  "1"
                "imba_wisp_overcharge_721"  "1"
                "imba_wisp_swap_spirits"  "1"
                "imba_wisp_relocate"  "1"
            }
            "hero_witch_doctor"
            {
                "imba_witch_doctor_paralyzing_cask"  "1"
                "imba_witch_doctor_voodoo_restoration"  "1"
                "imba_witch_doctor_maledict"  "1"
                "imba_witch_doctor_death_ward"  "1"
            }
            "hero_wraith_king"
            {
                "imba_wraith_king_wraithfire_blast"  "1"
                "imba_wraith_king_vampiric_aura"  "1"
                "imba_wraith_king_mortal_strike"  "1"
                "imba_wraith_king_kingdom_come"  "1"
                //"imba_wraith_king_wraith_soul_strike"  "1"      //not a good spell
                "imba_wraith_king_reincarnation"  "1"
            }
            "hero_zuus"
            {
                "imba_zuus_arc_lightning"  "1"
                "imba_zuus_lightning_bolt"  "1"
                "imba_zuus_static_field"  "1"
                "imba_zuus_cloud"  "1"
                "imba_zuus_nimbus_zap"  "1"
                "imba_zuus_thundergods_wrath"  "1"
            }

        }
        // The IMBA skills in LoD
        "superop" {
            "radiant_jungle_op"
            {
                  "spawn_small_camp_op"            "1"
                  "spawn_medium_camp_op"           "1"
                  "spawn_large_camp_op"            "1"
                  "spawn_ancient_camp_op"          "1"
            }

            "angel_arena_tome_op"
            {
                  "angel_arena_tome_lvlup_op"  "1"
                  "angel_arena_tome_gods_op"  "1"
                  "angel_arena_tome_int_op"  "1"
                  "angel_arena_tome_str_op"  "1"
                  "angel_arena_tome_agi_op"  "1"
                  "angel_arena_tome_med_op"  "1"
            }

            "imba_towers_700_and_survivor"
            {
                  "imba_tower_healing_tower"    "1"
                  //"imba_roshan_fury_op"      "1"
                  "spell_lab_survivor_cooldown_op"    "1"
                  "spell_lab_survivor_spell_boost_op" "1"
            }

            "imba_towers_weak"
            {
                "omniknight_degen_aura_tower"   "1"
                "omniknight_degen_aura_damage_tower"   "1"
                "vassal_shield"   "1"
                "titan_command_aura"    "1"
                "bahamut_reckoning_aura"  "1"
                "imba_tower_atrophy"   "1"
                "imba_tower_force"   "1"
                "imba_tower_mana_burn"   "1"
                "imba_tower_mana_flare"   "1"
                "imba_tower_mindblast"   "1"
                "imba_tower_permabash"   "1"
                "imba_tower_plague"   "1"
                "imba_tower_spacecow"   "1"
            }

            "imba_towers_medium"
            {
                  "invoker_retro_invisibility_aura_tower"      "1"
                  "imba_tower_plasma_field"     "1"
                  "imba_tower_death_pulse"      "1"
                  "imba_tower_berserk"   "1"
                  "imba_tower_spell_shield"   "1"
                  "imba_tower_hex_aura"   "1"
                  "imba_tower_vicious"   "1"
                  "imba_tower_nature"   "1"
                  "imba_tower_chrono"   "1"
                  "summoner_tesla_coil"   "1"
                  "lich_cold_aura"    "1"
                  "imba_tower_laser"   "1"
                  "imba_tower_disease"   "1"
            }
            "imba_towers_strong"
            {
                  "imba_tower_multihit"   "1"
                  "imba_tower_sniper"   "1"
                  "imba_tower_grievous_wounds"   "1"
                  "imba_tower_essence_drain"   "1"
                  "imba_tower_machinegun"   "1"
                  "imba_tower_salvo"   "1"
                  "imba_tower_fervor"   "1"
                  "imba_tower_split"   "1"
            }

            "memes_reborn_op"{
                  "lina_banana"     "1"
                  "lina_blazer"     "1"
                  "lina_coconut"    "1"
                  "lina_grapefruit" "1"
            }

            "survivor_op"
            {
                  "spell_lab_survivor_agi_survival" "1"
                  "spell_lab_survivor_armor" "1"
                  "spell_lab_survivor_attack_range" "1"
                  "spell_lab_survivor_attack_speed" "1"
                  "spell_lab_survivor_bash" "1"
                  "spell_lab_survivor_cast_range" "1"
                  "spell_lab_survivor_cooldown" "1"
                  "spell_lab_survivor_critical" "1"
                  "spell_lab_survivor_damage_boost" "1"
                  "spell_lab_survivor_evasion" "1"
                  "spell_lab_survivor_int_survival" "1"
                  "spell_lab_survivor_life_steal" "1"
                  "spell_lab_survivor_mana_burn" "1"
                  "spell_lab_survivor_mana_regen" "1"
                  "spell_lab_survivor_spell_boost" "1"
                  "spell_lab_survivor_spell_vamp" "1"
                  "spell_lab_survivor_str_survival" "1"
                  "spell_lab_survivor_tenacity" "1"
            }

            "spell_lab_souls_op"
            {
                "spell_lab_souls_agi" "1"
                "spell_lab_souls_armor" "1"
                "spell_lab_souls_attack_range" "1"
                "spell_lab_souls_attack_speed" "1"
                "spell_lab_souls_cast_range" "1"
                "spell_lab_souls_cooldown" "1"
                "spell_lab_souls_damage" "1"
                "spell_lab_souls_evasion" "1"
                "spell_lab_souls_int" "1"
                "spell_lab_souls_mana_regen" "1"
                "spell_lab_souls_spell_boost" "1"
                "spell_lab_souls_str" "1"
                "spell_lab_souls_tenacity" "1"
             }

            "basic_abilities"
            {
                  "basic_tenacity_bonus_op"   "1"
                  //"basic_willpower_bonus_op"   "1"
                  "basic_mana_bonus_op"   "1"
                  "basic_health_bonus_op" "1"
                  "basic_gpm_bonus_op" "1"
                  "basic_movespeed_bonus_op" "1"
                  "basic_xpm_bonus_op" "1"
                  "basic_spell_amp_bonus_op"   "1"
                  "basic_stat_gain_bonus_op"   "1"
                  "basic_stat_bonus_op"   "1"
                  "ability_mjolnir_op"    "1"
                  "ability_blademail_op" "1"
                  "ability_wards_op" "1"
                  "bash_reflect_op" "1"
                  //"redux_pocket_tower_ability"       "1" // Re-enable later
                  //"basic_bat_op" "0"
                  //"basic_bat_reduction_op" "0"  // breaks all sorts of things
            }

            "singlePlayer_actives" {
                  "abyssal_underlord_dark_rift_op"    "1"
                  "axe_berserkers_call_op"            "1"
                  "arc_warden_tempest_double_op"      "1"
                  "batrider_flamebreak_op"            "1"
                  //"bloodseeker_thirst_lod_op"         "1" // TODO: Make it OP
                  "dark_seer_vacuum_op"               "1"
                  "global_stun"                       "1"
                  "invoker_chaos_meteor_op"           "1"
                  "lich_chain_frost_op"               "1"
                  "tusk_walrus_kick_op"               "1"
				  "windrunner_gale_force_op"          "1"
            }
            "singlePlayer_actives_2" {
                  "disruptor_kinetic_field_OP"              "1"
                  "disruptor_glimpse_OP"                    "1"
                  "ogre_magi_bloodlust_op"                  "1"
                  "ogre_magi_bloodlust_reverse"             "1"
                  "zuus_arc_lightning_op"                   "1"
                  "zuus_lightning_bolt_global"              "1"
                  "lone_druid_savage_roar_op"               "1"
                  "tinker_heat_seeking_missile_redux"       "1"
                  "shadow_shaman_mass_serpent_ward_redux"   "1"
                  "legion_commander_duel_redux"             "1"
                  "mirana_invis_redux"                      "1"
                  "crystal_maiden_brilliance_aura_redux"    "1"
                  "faceless_void_chronosphere_redux"        "1"
            }
            "singlePlayer_actives_3" {
                  "android_cluster_rockets_OP"        "1"
                  "angel_arena_rifle_OP"              "1"
                  "serpent_queen_ball_lightning_op"   "1"
                  "shards_of_truesight_lod_OP"        "1"
                  "garden_red_flower_base_OP"         "1"
                  "hylonome_eldritch_pull_op"         "1"
                  "force_dash_lod_OP"                 "1"
                  "zulf_typhoon_OP"                   "1"
                  "android_pocket_factory"            "1"
                  "aabs_nightshadow_op"               "1"
            }
            "singlePlayer_actives_4" {
                  "pangolier_swashbuckle_op"          "1"
                  "faceless_void_chronosphere_op"     "1"
                  "mars_arena_of_blood_op"            "1"
                  "grimstroke_soul_chain_friendly"    "1"
                  "grimstroke_soul_chain_op"          "1"
                  //"clinkz_burning_army_op"          "1"      // BUGGED Skeletons dont spawn
                  "summon_zombie"                     "1"
                  "courier_shield"                    "1"
                  "courier_burst"                     "1"
                  "holdout_culling_blade"                "1"
            }

            "singlePlayer_passive_4" {
                  "bounty_hunter_jinada_op"                 "1"
                  "bristleback_warpath_op"                  "1"
                  "templar_assassin_psi_blades_op"          "1"
                  "abyssal_underlord_atrophy_aura_op"     "1"       // needs updating to match new version
				  "tornado_tempest"						"1"
				  "miniboss_reflect"					"1"
				  "miniboss_unyielding_shield"			"1"
				  "miniboss_radiance"					"1"
				  "meepo_divided_we_stand"            "1"
            }

            "singlePlayer_passive" {
                  "imba_tower_aegis_OP"                           "1"
                  //"erra_grave_guard_op"                         "1"  //Has been deleted since we brought in the LUA versions
                  "dragon_knight_dragon_blood_OP"                 "1"
                  "alchemist_goblins_greed_op"                    "1"
                  "shredder_reactive_armor_op"                    "1"
                  "nevermore_necromastery_op"                     "1"
                  //"imba_juggernaut_healing_ward_passive_redux"  "1"
                  "obsidian_destroyer_essence_aura_lod_health"    "1"
                  //"linkens_guard_lod"                           "1"
                  "brewmaster_earth_spell_immunity"               "1"
                  "backdoor_protection"                           "1"
                  "neutral_spell_immunity"                        "1"
                  "creep_siege"                                   "1"
            }
            "singlePlayer_passive_2" {
                  "angel_arena_razor_power_OP"        "1"
                  "angel_arena_nether_ritual"         "1"
                  "ebf_clinkz_trickshot_passive"      "1"
                  "lord_of_lightning_holy_wrath_OP"   "1"
                  "octarine_vampirism_lod_OP"         "1"
                  "aether_range_lod_OP"               "1"
                  "ebf_rubick_arcane_echo_OP"         "1"
                  "frost_lord_freezing_OP"            "1"
                  "pudge_flesh_heap_fiery_soul"       "1"
            }
            "singlePlayer_passive_3" {
                  "zhanhun_op"                        "1"
                  "jingtong_op"                       "1"
                  "spell_reflect_op"                  "1"
                  "master_magic_op"                   "1"
                  "channel_earthquake_op"             "1"
                  "chi_strike_sp"                     "1"
                  "metamorphosis_op"                  "1"
                  "death_prophet_witchcraft_op"       "1"
                  "invoker_sun_strike_lod_op"         "1"
            }

            "mega_ultimates" {
                  "mega_black_hole"       "1"
                  "armageddon"            "1"
                  "mega_chronosphere"     "1"
                  "mega_eclipse"          "1"
                  "floor_is_lava"         "1"
                  "mega_freezing_field"   "1"
                  "mega_suicide"          "1"
                  "mega_omni_slash"       "1"
                  "mega_call_down"        "1"
                  "mega_flare"            "1"
            }

      }
    }
    "heroToSkillMap" {
        "npc_dota_hero_abaddon" {
			"1"  "abaddon_the_quickening"
        }

		"npc_dota_hero_abyssal_underlord" {
            "1"            "abyssal_underlord_dark_rift"
			"2"            "abyssal_underling_archer_aoe"
			"3"            "abyssal_underling_warrior_last_will"
			"4"            "abyssal_underling_warrior_mana_burn"
        }

		"npc_dota_hero_alchemist" {
            "1"  "alchemist_transmuted_scepter"
            "2"  "alchemist_aghnaim_magic_redux"
        }

		"npc_dota_hero_ancient_apparition" {
			"1"			  "ancient_apparition_ice_age"
        }

		"npc_dota_hero_antimage" {
			"1"			  "antimage_mana_overload"
        }

        "npc_dota_hero_arc_warden" {
			"1"  "arc_warden_tempest_recall"
			"2"  "arc_warden_scepter"
        }

		"npc_dota_hero_axe" {
			"1"            "axe_one_man_army"
        }

		// "npc_dota_hero_bane" {
			// "Ability1"            "bane_enfeeble"
			// "Ability2"            "bane_brain_sap"
            // "Ability3"            "bane_nightmare"
            // "Ability4"            "bane_fiends_grip"
			// "Ability5"            "bane_ichor_of_nyctasha"
		// }

		"npc_dota_hero_batrider" {
			"1"            "batrider_stoked"
		}

		"npc_dota_hero_beastmaster" {
			"1"			  "beastmaster_mark_of_the_beast"
			"2"           "beastmaster_hawk_perch"
			"3"           "beastmaster_boar_poison"
			"4"           "beastmaster_greater_boar_poison"
        }

		"npc_dota_hero_bloodseeker" {
            "1"            "bloodseeker_thirst_lod"
            "2"            "bloodseeker_blood_bath2"
        }

		"npc_dota_hero_bounty_hunter" {
			"1"      "bounty_hunter_cutpurse"
        }

		"npc_dota_hero_brewmaster" {
			"1"           "brewmaster_drunken_haze"
            "2"           "brewmaster_earth_hurl_boulder"
            "3"           "brewmaster_earth_pulverize"
            "4"           "brewmaster_storm_wind_walk"
            "5"           "brewmaster_storm_dispel_magic"
			"6"           "brewmaster_storm_cyclone"
            "7"           "brewmaster_fire_permanent_immolation"
            "8"			  "brewmaster_fire_phase"
			"9"			  "brewmaster_void_astral_pulse"
			"10"		  "brewmaster_void_astral_pull"
        }

		// "npc_dota_hero_bristleback" {
			// "Ability1"		"bristleback_viscous_nasal_goo"
			// "Ability2"		"bristleback_quill_spray"
			// "Ability3"		"bristleback_bristleback"
			// "Ability4"		"bristleback_warpath"
			// "Ability5"		"bristleback_hairball"
		// }

		"npc_dota_hero_broodmother" {
			"1"		"broodmother_silken_bola"
			"2"     "broodmother_poison_sting"
        }

		"npc_dota_hero_centaur" {
			"1"        "centaur_horsepower"
        }

		"npc_dota_hero_chaos_knight" {
            "1"        "chaos_knight_phantasmagoria"
		}

		"npc_dota_hero_chen" {
			"1"        "chen_test_of_faith"
        }

        "npc_dota_hero_clinkz" {
			"1"        "clinkz_searing_arrows"
        }

		"npc_dota_hero_crystal_maiden" {
			"1"			  "crystal_maiden_let_it_go"
        }

		"npc_dota_hero_dark_seer" {
			"1"            "dark_seer_quick_wit"
			"2"            "dark_seer_heart_of_battle"
		}

		// "npc_dota_hero_dark_willow" {
            // "Ability1"  "dark_willow_bramble_maze"
            // "Ability2"  "dark_willow_shadow_realm"
            // "Ability3"  "dark_willow_cursed_crown"
            // "Ability4"  "dark_willow_bedlam"
            // "Ability5"  "dark_willow_terrorize"
			// "Ability6"  "dark_willow_pixie_dust"
        // }

		"npc_dota_hero_dawnbreaker" {
			"1"  "dawnbreaker_unbreakable"
        }

		"npc_dota_hero_dazzle" {
			"1"        "dazzle_nothl_boon"
            "2"        "dazzle_weave"
            "3"        "dazzle_good_juju"
            "4"        "dazzle_bad_juju_redux"
			"5"		   "dazzle_rain_of_vermin"
        }

		"npc_dota_hero_death_prophet" {
			"1"            "death_prophet_spirit_collector"
			"2"            "death_prophet_mourning_ritual"
			// "3"            "death_prophet_innate_healing_mastery"
        }

		"npc_dota_hero_disruptor" {
			"1"		"disruptor_kinetic_field"
			"2"		"disruptor_kinetic_fence"
		}

		"npc_dota_hero_doom_bringer" {
            "1"            "doom_bringer_devour_lod"
			"2"            "doom_bringer_devils_bargain"
        }

		// "npc_dota_hero_dragon_knight" {
            // "Ability1"  "dragon_knight_breathe_fire"
            // "Ability2"  "dragon_knight_dragon_tail"
            // "Ability3"  "dragon_knight_dragon_blood"
            // "Ability4"  "dragon_knight_elder_dragon_form"
			// "Ability5"	"dragon_knight_fireball"
			// "Ability6"  "dragon_knight_inherited_vigor"
        // }

		"npc_dota_hero_drow_ranger" {
			"1"       "drow_ranger_silence"
			"2"       "drow_ranger_vantage_point"
			"3"       "drow_splitshot"
		}

		"npc_dota_hero_earthshaker" {
            "1"      "earthshaker_aftershock_lod"
            "2"      "earthshaker_slugger"
        }

		"npc_dota_hero_elder_titan" {
            "1"		"elder_titan_echo_stomp_spirit"
			"2"     "elder_titan_momentum"
        }

		"npc_dota_hero_enigma" {
			"1"      "enigma_event_horizon"
			"2"      "enigma_splitting_image"
		}

		"npc_dota_hero_faceless_void"
        {
            "1"  "faceless_void_backtrack"
            "2"  "faceless_void_chronosphere"
			"3"	 "faceless_void_time_zone"
        }

		"npc_dota_hero_furion" {
			"1"		"furion_greater_sprout"
			"2"     "furion_arboreal_might"
			"3"     "furion_hedgerow"
        }

		"npc_dota_hero_grimstroke" {
			"1"		"grimstroke_ink_over"
        }

		"npc_dota_hero_gyrocopter"
        {
            "1"  "side_gunner_redux"
        }

		"npc_dota_hero_huskar" {
            "1"            "huskar_berserkers_blood_lod"
			"2"            "huskar_inner_vitality"
        }

		"npc_dota_hero_invoker" {
            "1"            "invoker_alacrity_ad"
            "2"            "invoker_chaos_meteor_ad"
            "3"            "invoker_cold_snap_ad"
            "4"            "invoker_emp_ad"
            "5"            "invoker_forge_spirit_ad"
            "6"            "invoker_ghost_walk_ad"
            "7"            "invoker_ice_wall_ad"
            "8"            "invoker_sun_strike_ad"
            "9"            "invoker_tornado_ad"
            "10"           "invoker_deafening_blast_ad"
        }

		"npc_dota_hero_jakiro" {
			"1"		"jakiro_liquid_fire"
			"2"		"jakiro_liquid_ice"
		}

		"npc_dota_hero_juggernaut" {
			"1"            "juggernaut_bladeform"
        }

		"npc_dota_hero_keeper_of_the_light" {
            "1"  "keeper_of_the_light_chakra_magic_cooldown"
            "2"  "keeper_of_the_light_mana_leak"
            "3"  "keeper_of_the_light_recall"
            "4"  "keeper_of_the_light_innate_redux"
			"5"	 "keeper_of_the_light_radiant_bind"
        }

		"npc_dota_hero_kunkka" {
			"1"   "kunkka_torrent_storm"
		}

		"npc_dota_hero_leshrac" {
            "1"    "leshrac_chronoptic_nourishment"
        }

		"npc_dota_hero_lich" {
            "1"       "lich_frost_armor"
			"2"		  "lich_dark_sorcery"
			"3"		  "lich_frost_aura"
        }

		"npc_dota_hero_life_stealer" {
            "1"           "life_stealer_rage"
            "2"           "life_stealer_assimilate"
			"3"			  "life_stealer_unfettered"
			"4"           "life_stealer_corpse_eater"
        }

		"npc_dota_hero_lina" {
			"1"          "lina_slow_burn"
		}

		"npc_dota_hero_lone_druid" {
			"1"     "lone_druid_bear_necessities"
			"2"     "lone_druid_entangling_claws"
			"3"     "lone_druid_rabid"
			"4"     "lone_druid_true_form_battle_cry"
        }

		"npc_dota_hero_luna" {
            "1"		"luna_lunar_grace"
        }

		"npc_dota_hero_lycan" {
			"1"		"lycan_summon_wolves_critical_strike"
			"2"     "lycan_summon_wolves_bash"
			"3"     "lycan_summon_wolves_hamstring"
			"4"     "lycan_summon_wolves_hightail"
			"5"     "lycan_summon_wolves_invisibility"
		}

		"npc_dota_hero_magnataur" {
			"1"			  "magnus_strength_of_joelrak"
        }

		"npc_dota_hero_marci" {
			"1"		"marci_guardian"
			"2"		"marci_bodyguard"
        }

		"npc_dota_hero_medusa" {
			"1"     "medusa_venomed_volley"
		}

		"npc_dota_hero_meepo" {
            "1"        "meepo_geostrike"
			"2"        "meepo_pack_rat"
        }

		"npc_dota_hero_mirana" {
            "1"           "mirana_invis"
			"2"			  "mirana_starfall_lod"
			"3"           "mirana_solar_flare"
        }

		"npc_dota_hero_morphling"
        {
            "1"  "morph_int_str_redux"
            "2"  "morph_str_int_redux"
            "3"  "morph_agi_int_redux"
            "4"  "morph_int_agi_redux"
			"5"  "morphling_ebb"
			"6"  "morphling_flow"
        }

		"npc_dota_hero_muerta" {
			"1"  "muerta_ofrenda"
		}

		"npc_dota_hero_naga_siren" {
			"1"		"naga_siren_rip_tide"
			"2"		"naga_siren_deluge"
			"3"     "naga_siren_crit"
		}

		"npc_dota_hero_necrolyte"
        {
			"1"  "necrolyte_sadist_lod"
        }

		"npc_dota_hero_night_stalker"
        {
            "1"  "night_stalker_innate_redux"
			"2"  "night_stalker_night_reign"
        }

		"npc_dota_hero_nyx_assassin"
        {
            "1"  "nyx_assassin_burrow_redux"
			"2"  "nyx_assassin_innate_mana_burn"
			"3"  "nyx_assassin_mana_burn"
        }

		"npc_dota_hero_obsidian_destroyer" {
            "1"           "obsidian_destroyer_astral_imprisonment_redux"
            "2"           "obsidian_destroyer_essence_aura_lod"
            "3"           "obsidian_destroyer_essence_aura_redux"
			"4"			  "obsidian_destroyer_essence_aura"
        }

		"npc_dota_hero_ogre_magi" {
            "1"            "ogre_magi_multicast_lod"
        }

		"npc_dota_hero_omniknight" {
			"1"			  "omniknight_angelic_flight"
			"2"           "omniknight_healing_hammer"
			"3"           "omniknight_pacify"
			"4"           "omniknight_repel"
        }

		"npc_dota_hero_oracle" {
			"1"    "oracle_clairvoyant_cure"
			"2"    "oracle_clairvoyant_curse"
		}

		"npc_dota_hero_phoenix" {
			"1"   "phoenix_dying_light"
		}

		"npc_dota_hero_queenofpain" {
            "1"   "queenofpain_masochist"
			"2"   "queenofpain_succubus"
        }

		"npc_dota_hero_razor" {
			"1"   "razor_dynamo"
		}

		"npc_dota_hero_riki" {
            "1"           "riki_permanent_invisibility"
			"2"			  "riki_poison_dart"
            "3"           "riki_backstab_lod"
        }

		"npc_dota_hero_rubick" {
            "1"        "rubick_null_field"
        }

		"npc_dota_hero_shadow_demon" {
			"1"		"shadow_demon_soul_catcher"
			"2"     "shadow_demon_shadow_servant"
        }

		"npc_dota_hero_shadow_shaman" {
			"1"		"shadow_shaman_serpentine"
        }

		"npc_dota_hero_shredder" {
			"1"    "shredder_chakram_2"
			"2"    "shredder_twisted_chakram"
		}

		"npc_dota_hero_silencer" {
            "1"            "silencer_global_break"
            "2"            "silencer_global_disarm"
        }

		"npc_dota_hero_skeleton_king" {
            "1"            "skeleton_king_bone_guard"
            "2"            "skeleton_king_spectral_blade"
        }

		"npc_dota_hero_skywrath_mage"
        {
            "1" "skywrath_mage_concussive_break"
			"2"	"skywrath_mage_shield_of_the_scion"
			"3" "skywrath_mage_staff_of_the_scion"
        }

		"npc_dota_hero_slark" {
            "1"            "slark_essence_shift_intellect_lod"
            "2"            "slark_essence_shift_strength_lod"
            "3"            "slark_essence_shift_agility_lod"
			"4"			   "slark_fish_bait"
        }

		"npc_dota_hero_spirit_breaker" {
            "1"        "spirit_breaker_empowering_haste"
			"2"        "spirit_breaker_knockback_amp"
        }

		"npc_dota_hero_storm_spirit" {
			"1"		"storm_spirit_electric_rave"
        }

		"npc_dota_hero_sven" {
            "1"     "sven_wrath_of_god"
        }

        "npc_dota_hero_techies" {
			"1"		"techies_remote_mines"
			"2"		"techies_stasis_trap"
			"3"     "techies_spoons_stash"
			"4"     "techies_squees_scope"
        }

		"npc_dota_hero_tidehunter" {
			"1"		"tidehunter_arm_of_the_deep"
			"2"     "tidehunter_krill_eater"
        }

		"npc_dota_hero_tinker" {
            "1"            "tinker_heat_seeking_missile"
        }

		"npc_dota_hero_tiny" {
            "1"            "tiny_grow_lod"
            "2"            "tiny_grow_lod_redux"
			"3"            "tiny_insurmountable"
			"4"            "tiny_rocksteady"
        }

		"npc_dota_hero_troll_warlord" {
			"1"		"troll_warlord_rampage"
        }

		"npc_dota_hero_tusk" {
            "1"        "tusk_tag_team"
            "2"        "tusk_frozen_sigil"
			"3"        "tusk_drinking_buddies"
        }

		"npc_dota_hero_undying"
        {
            "1" "undying_decay_agi"
            "2" "undying_decay_int"
            "3" "undying_tombstone_zombie_deathstrike"
        }

		"npc_dota_hero_ursa" {
            "1"            "ursa_fury_swipes_lod"
            "2"            "ursa_enrage_old"
			"3"            "ursa_bear_down"
			"4"            "ursa_maul"
        }

		"npc_dota_hero_vengefulspirit" {
           "1"         "vengefulspirit_soul_strike"
        }

		"npc_dota_hero_venomancer" {
			"1"		"venomancer_latent_poison"
			"2"		"venomancer_poison_nova"
        }

		"npc_dota_hero_void_spirit" {
            "1"         "void_spirit_symmetry"
        }

		"npc_dota_hero_warlock" {
			"1"          "warlock_black_grimoire"
			"2"          "warlock_imp_explode"
			"3"          "warlock_imp_explode_major"
		}

		"npc_dota_hero_winter_wyvern" {
			"1"           "winter_wyvern_dragon_sight"
			"2"           "winter_wyvern_essence_of_the_blueheart"
		}

		// "npc_dota_hero_templar_assassin" {
            // "Ability1"		"templar_assassin_refraction"
			// "Ability2"		"templar_assassin_meld"
			// "Ability3"		"templar_assassin_psi_blades"
			// "Ability4"		"templar_assassin_psionic_trap"
			// "Ability5"		"templar_assassin_trap_teleport"
        // }

        // "npc_dota_hero_snapfire" {
            // "Ability1"        "snapfire_scatterblast"
            // "Ability2"        "snapfire_firesnap_cookie"
            // "Ability3"        "snapfire_lil_shredder"
			// "Ability4"		  "snapfire_gobble_up"
            // "Ability5"        "snapfire_mortimer_kisses"
        // }

        // "npc_dota_hero_zuus" {
            // "Ability1"            "zuus_arc_lightning"
            // "Ability2"            "zuus_lightning_bolt"
            // "Ability3"            "zuus_static_field"
            // "Ability4"            "zuus_cloud"
            // "Ability5"            "zuus_thundergods_wrath"
			// "Ability6"			  "zuus_heavenly_jump"
			// "Ability7"			  "zuus_lightning_hands"
        // }

        // "npc_dota_hero_legion_commander" {
            // "Ability1"            "legion_commander_overwhelming_odds"
            // "Ability2"            "legion_commander_press_the_attack"
            // "Ability3"            "legion_commander_moment_of_courage"
            // "Ability4"            "legion_commander_duel"
        // }

        // "npc_dota_hero_pangolier" {
            // "Ability1"                          "pangolier_swashbuckle"
            // "Ability2"                          "pangolier_shield_crash"
            // "Ability3"                          "pangolier_lucky_shot"
            // "Ability4"                          "pangolier_gyroshell"
			// "Ability5"							"pangolier_rollup"
      // }

        // "npc_dota_hero_slardar" {
            // "Ability1"            "slardar_sprint"
            // "Ability2"            "slardar_slithereen_crush"
			// "Ability3"            "slardar_bash"
            // "Ability4"            "slardar_amplify_damage"
        // }

        // "npc_dota_hero_pudge" {
            // "Ability1"            "pudge_meat_hook"
            // "Ability2"            "pudge_rot"
            // "Ability3"            "pudge_flesh_heap"
            // "Ability4"            "pudge_dismember"
        // }

        // "npc_dota_hero_monkey_king"
        // {
            // "Ability1" "monkey_king_boundless_strike"
            // "Ability2"  "monkey_king_tree_dance"
            // "Ability3"  "monkey_king_primal_spring"
            // "Ability4"  "monkey_king_jingu_mastery"
            // "Ability5"  "monkey_king_wukongs_command"
        // }
        // "npc_dota_hero_mars"
        // {
            // "Ability1" "mars_spear"
            // "Ability2"  "mars_gods_rebuke"
            // "Ability3"  "mars_bulwark"
            // "Ability4"  "mars_arena_of_blood"
        // }

        // "npc_dota_hero_sand_king"
        // {
            // "Ability1" "sandking_burrowstrike"
            // "Ability2"  "sandking_epicenter"
            // "Ability3"  "sandking_caustic_finale"
            // "Ability4"  "sandking_sand_storm"
			// "Ability5"	"sandking_scorpion_strike"
        // }
        // "npc_dota_hero_phantom_lancer"
        // {
            // "Ability1"  "phantom_lancer_spirit_lance"
			// "Ability2" "phantom_lancer_doppelwalk"
            // "Ability3"  "phantom_lancer_phantom_edge"
            // "Ability4"  "phantom_lancer_juxtapose"
        // }

        // "npc_dota_hero_phantom_assassin"
        // {
            // "Ability1"  "phantom_assassin_stifling_dagger"
            // "Ability2"  "phantom_assassin_phantom_strike"
            // "Ability3"  "phantom_assassin_blur"
            // "Ability4"  "phantom_assassin_coup_de_grace"
			// "Ability5"	"phantom_assassin_fan_of_knives"
        // }

        // "npc_dota_hero_hoodwink"
        // {
            // "Ability1"  "hoodwink_acorn_shot"
            // "Ability2"  "hoodwink_bushwhack"
            // "Ability3"  "hoodwink_scurry"
            // "Ability4"  "hoodwink_sharpshooter"
			// "Ability5"	"hoodwink_decoy"
			// "Ability6"	"hoodwink_hunters_boomerang"
        // }

         // "npc_dota_hero_treant"
        // {
            // "Ability1"  "treant_natures_grasp"
            // "Ability2"  "treant_leech_seed"
            // "Ability3"  "treant_living_armor"
            // "Ability4"  "treant_eyes_in_the_forest"
            // "Ability5"  "treant_natures_guise"
            // "Ability6"  "treant_overgrowth"
        // }

		// "npc_dota_hero_primal_beast" {
            // "Ability1"  "primal_beast_onslaught"
            // "Ability2"  "primal_beast_trample"
            // "Ability3"  "primal_beast_uproar"
            // "Ability4"  "primal_beast_rock_throw"
            // "Ability5"  "primal_beast_pulverize"
        // }

		// "npc_dota_hero_nevermore" {
			// "Ability1"		"nevermore_shadowraze1"
			// "Ability2"		"nevermore_shadowraze2"
			// "Ability3"		"nevermore_shadowraze3"
			// "Ability4"		"nevermore_necromastery"
			// "Ability5"		"nevermore_dark_lord"
			// "Ability6"		"nevermore_requiem"
			// "Ability7"		"nevermore_frenzy"
		// }

		// "npc_dota_hero_visage" {
			// "Ability1"		"visage_grave_chill"
			// "Ability2"		"visage_soul_assumption"
			// "Ability3"		"visage_gravekeepers_cloak"
			// "Ability4"		"visage_silent_as_the_grave"
			// "Ability5"		"visage_summon_familiars"
			// "Ability6"		"visage_summon_familiars_stone_form"
		// }
    }
}
