"Bans" {
    "BannedTowerCombinations" {
        "imba_tower_multihit" {
            "imba_tower_machinegun"              "1"
        }
    }

    // List of categories to use with the categories bans
    "Categories" {
        // List of spells that can be spammed easily
        // 1 to reference a spell
        // 2 to reference another list (note: Do NOT create recursion, there is no recursion checking!)
        "SpammableSpells" {
            // Ban ToggleSpells
            "ToggleSpells"                      "2"

            // Ban skillz
            "abaddon_aphotic_shield"            "1"
            "abaddon_death_coil"                "1"
            "ancient_apparition_ice_vortex"     "1"
            "antimage_blink"                    "1"
            "arc_warden_spark_wraith"           "1"
            "axe_battle_hunger"                 "1"
            "batrider_sticky_napalm"            "1"
            "bloodseeker_blood_rage"            "1"
            "bounty_hunter_track"               "1"
            "bristleback_quill_spray"           "1"
            "bristleback_viscous_nasal_goo"     "1"
            "chaos_knight_reality_rift"         "1"
            "dazzle_shadow_wave"                "1"
            "earthshaker_enchant_totem"         "1"
            //"elder_titan_ancestral_spirit"      "1"
            "gyrocopter_rocket_barrage"         "1"
            "leshrac_lightning_storm"           "1"
            "lich_frost_armor"                  "1"
            "lion_mana_drain"                   "1"
            "luna_lucent_beam"                  "1"
            "necrolyte_death_pulse"             "1"
            "oracle_purifying_flames"           "1"
            "phantom_assassin_phantom_strike"   "1"
            "puck_phase_shift"                  "1"
            "pugna_nether_blast"                "1"
            "queenofpain_blink"                 "1"
            "shadow_demon_shadow_poison"        "1"
            "shredder_timber_chain"             "1"
            "skywrath_mage_arcane_bolt"         "1"
            "slark_dark_pact"                   "1"
            "storm_spirit_static_remnant"       "1"
            "templar_assassin_meld"             "1"
            "tidehunter_anchor_smash"           "1"
            "tinker_rearm"                      "1"
            //"treant_natures_guise"              "1" // it's a passive now
            "undying_decay"                     "1"
            "venomancer_plague_ward"            "1"
            "weaver_shukuchi"                   "1"
            "zuus_arc_lightning"                "1"
        }

        // Toggle spells
        "ToggleSpells" {
            "ability_wards"                     "1"
            "ability_wards_op"                  "1"
            "cherub_synthesis"                  "1"
            "courier_go_to_secretshop"          "1"
            "courier_return_stash_items"        "1"
            "courier_return_to_base"            "1"
            "courier_take_stash_items"          "1"
            "courier_transfer_items"            "1"
            "elder_titan_return_spirit"         "1"
            "forest_troll_high_priest_heal"     "1"
            //"furion_teleportation"              "1" // not a toggle
            //"harpy_storm_chain_lightning"       "1" // not a toggle
            "holdout_multishot"                 "1"
            "leshrac_pulse_nova"                "1"
            "life_stealer_assimilate"           "1"
            "life_stealer_consume"              "1"
            "life_stealer_infest"               "1" // You get consume, which can be spammmmed
            "lod_item_power_treads"             "1" // Amazing when toggling aftershock!
            //"medusa_mana_shield"                "1" // it's a passive
            "medusa_split_shot"                 "1"
            //"meepo_poof"                        "1" // not a toggle
            "morph_agi_int_redux"               "1"
            "morph_int_agi_redux"               "1"
            "morph_int_str_redux"               "1"
            "morph_str_int_redux"               "1"
            "morphling_morph_agi"               "1"
            "morphling_morph_str"               "1"
            "nyx_assassin_burrow"               "1" // Why you do this, valve?
            "nyx_assassin_burrow_redux"         "1"
            "proteus_jet"                       "1"
            "pudge_rot"                         "1"
            //"riki_blink_strike"                 "1" // not a toggle, charge based though
            //"shredder_chakram"                  "1" // not a toggle
            "spectre_reality"                   "1" // Can be used over and over
            "techies_focused_detonate"          "1"
            "troll_warlord_berserkers_rage"     "1"
            //"wisp_overcharge"                   "1" // not a toggle anymore
            "witch_doctor_voodoo_restoration"   "1"
        }
    }

    // These are groups of spells where none of these can be used together
    "BannedGroups" {
        // The one hit combo group
        "1" {
            "alexander_godfall"                 "1"
            //"bounty_hunter_jinada"              "1" // doesnt crit anymore
            "brewmaster_drunken_brawler"        "1"
            //"clinkz_death_pact"                 "1" // doesnt grant damage
            "earthshaker_enchant_totem"         "1"
            "hero_one_punch"                    "1"
            "kunkka_tidebringer"                "1"
            "monkey_king_boundless_strike"      "1"
            "terrorblade_metamorphosis"         "1"
            "tiny_grow_lod"                     "1"
            "tiny_grow_lod_redux"               "1"
            "tusk_walrus_punch"                 "1"
            "ursa_overpower"                    "1"
            "weaver_geminate_attack"            "1"
            //"tiny_grow"                         "1"
        }

        // The mega range group
        "2" {
            "dragon_knight_elder_dragon_form"   "1"
            "sniper_take_aim"                   "1"
            "templar_assassin_psi_blades"       "1"
            "terrorblade_metamorphosis"         "1"
            "winter_wyvern_arctic_burn"         "1"
        }

        // Chemical Rages
        "3" {
            "alchemist_chemical_rage"            "1"
            "custom_bot_chemical_rage"           "1"
        }

        // Shadow Dances
        "4" {
            "custom_bot_shadow_dance"            "1"
            "slark_shadow_dance"                 "1"
        }

        // Bash
        "5" {
            "faceless_void_time_lock"               "1"
            "imba_tower_permabash"                  "1"
            "roshan_bash"                           "1"
            "slardar_bash"                          "1"
            "spirit_breaker_greater_bash"           "1"
            //"troll_warlord_berserkers_rage"         "1" // not a bash anymore
        }
        // Flesh heaps
        "6" {
            "angel_arena_tome_agi"                  "1"
            "angel_arena_tome_gods"                 "1"
            "angel_arena_tome_int"                  "1"
            "angel_arena_tome_med"                  "1"
            "angel_arena_tome_str"                  "1"
            "lina_banana_redux"                     "1"
            "lina_coconut_redux"                    "1"
            "lina_grapefruit_redux"                 "1"
            "pudge_flesh_heap"                      "1"
            "pudge_flesh_heap_agility"              "1"
            "pudge_flesh_heap_agility"              "1"
            "pudge_flesh_heap_armor"                "1"
            "pudge_flesh_heap_attack_range"         "1"
            "pudge_flesh_heap_cast_range"           "1"
            "pudge_flesh_heap_cooldown_reduction"   "1"
            "pudge_flesh_heap_int"                  "1"
            "pudge_flesh_heap_lifesteal"            "1"
            "pudge_flesh_heap_magic_resistance"     "1"
            "pudge_flesh_heap_move_speed"           "1"
            "pudge_flesh_heap_spell_amp"            "1"
            "pudge_flesh_heap_spell_lifesteal"      "1"
            "spell_lab_souls_agi"                   "1"
            "spell_lab_souls_armor"                 "1"
            "spell_lab_souls_attack_range"          "1"
            "spell_lab_souls_attack_speed"          "1"
            "spell_lab_souls_cast_range"            "1"
            "spell_lab_souls_cooldown"              "1"
            "spell_lab_souls_damage"                "1"
            "spell_lab_souls_damage"                "1"
            "spell_lab_souls_evasion"               "1"
            "spell_lab_souls_health_regen"          "1"
            "spell_lab_souls_int"                   "1"
            "spell_lab_souls_magic_resistance"      "1"
            "spell_lab_souls_mana_regen"            "1"
            "spell_lab_souls_move_speed"            "1"
            "spell_lab_souls_spell_boost"           "1"
            "spell_lab_souls_str"                   "1"
            "spell_lab_souls_vision"                "1"
            "spell_lab_survivor_agi_survival"       "1"
            "spell_lab_survivor_armor"              "1"
            "spell_lab_survivor_attack_range"       "1"
            "spell_lab_survivor_attack_speed"       "1"
            "spell_lab_survivor_bash"               "1"
            "spell_lab_survivor_cast_range"         "1"
            "spell_lab_survivor_cooldown"           "1"
            "spell_lab_survivor_critical"           "1"
            "spell_lab_survivor_damage_boost"       "1"
            "spell_lab_survivor_evasion"            "1"
            "spell_lab_survivor_health_regen"       "1"
            "spell_lab_survivor_int_survival"       "1"
            "spell_lab_survivor_life_steal"         "1"
            "spell_lab_survivor_magic_resistance"   "1"
            "spell_lab_survivor_mana_burn"          "1"
            "spell_lab_survivor_mana_regen"         "1"
            "spell_lab_survivor_move_speed"         "1"
            "spell_lab_survivor_spell_boost"        "1"
            "spell_lab_survivor_spell_vamp"         "1"
            "spell_lab_survivor_str_survival"       "1"
            "spell_lab_survivor_vision"             "1"
            //"pudge_flesh_heap_bonus_vision"       "1"
            //"pudge_flesh_heap_evasion"            "1"
        }
        // Cooldown manipulation abilities
        "7" {
            "death_prophet_witchcraft"                  "1"
            "dazzle_bad_juju_redux"                     "1"
            "jingtong"                                  "1"
            "jingtong_op"                               "1"
            "keeper_of_the_light_chakra_magic"          "1"      // lod's rearm + CD reduction talent.
            "keeper_of_the_light_chakra_magic_cooldown" "1"
            "master_magic"                              "1"      //Allowed you Master_magic + CD reduction + Nimbus or any global ability.
            "pudge_flesh_heap_cooldown_reduction"       "1"
            "spell_lab_souls_cooldown"                  "1"
            "spell_lab_survivor_cooldown"               "1"
            "tinker_rearm"                              "1"
            "veera_thrill_of_the_hunt"                  "1"
            "zhanhun"                                   "1"
            "zhanhun_op"                                "1"
            //"aabs_nightshadow"                        "1"
            //"holdout_gods_strength"                   "1"
            //"proteus_rarefaction"                     "1"
        }
        "8" {
            "spell_lab_void_step"                   "1"
            "spirit_breaker_greater_bash"           "1"
        }
    }

    "BannedTowerGroups" {
        "1" {
            "imba_tower_berserk"            "1"
            "imba_tower_essence_drain"      "1"
            "imba_tower_fervor"             "1"
            "imba_tower_machinegun"         "1"
            "imba_tower_multihit"           "1"
        }
    }


    // Stop multicast on these spells
    "noMulticast" {
		"ability_wards"                     "1"
		"ability_wards_op"                  "1"
		"abyssal_underlord_cancel_dark_rift"  "1" // wastes multicast cd
		"abyssal_underlord_cancel_dark_rift_oaa"  "1" // wastes multicast cd
		"alchemist_unstable_concoction_throw"  "1" // wastes multicast cd
		"ancient_apparition_ice_blast_release"  "1" // wastes multicast cd
		"ancient_priestess_spirit_link"     "1" // ability doesnt bounce to other players if multicasted
		"angel_arena_tome_agi"              "1"
		"angel_arena_tome_agi_op"           "1"
		"angel_arena_tome_gods"             "1"
		"angel_arena_tome_gods_op"          "1"
		"angel_arena_tome_int"              "1"
		"angel_arena_tome_int_op"           "1"
		"angel_arena_tome_lvlup"            "1"
		"angel_arena_tome_lvlup_op"         "1"
		"angel_arena_tome_med"              "1"
		"angel_arena_tome_med_op"           "1"
		"angel_arena_tome_str"              "1"
		"angel_arena_tome_str_op"           "1"
		"arc_warden_tempest_double"         "1" // bugs out
		"arcane_mastery"                    "1"
		"bane_nightmare_end"                "1" // wastes multicast cd
		"centaur_mount"                     "1" // bugs out
		"crystal_maiden_freezing_field_stop"  "1" // wastes multicast cd
		"dawnbreaker_converge"              "1" // wastes multicast cd
		"dawnbreaker_land"                  "1" // wastes multicast cd
		"earth_spirit_rolling_boulder"      "1" // bugs out
		"elder_titan_move_spirit"           "1" // wastes multicast cd
		"elder_titan_return_spirit"         "1" // wastes multicast cd
		"ember_spirit_activate_fire_remnant"  "1" // wastes multicast cd
		"enraged_wildkin_tornado"           "1" // multiplies
		"faceless_void_time_walk_reverse"   "1" // wastes multicast cd
		"furion_teleportation"              "1"
		"hoodwink_sharpshooter"             "1"
		"hoodwink_sharpshooter_release"     "1" // wastes multicast cd
		"invoker_cold_snap_lod"             "1"
		"item_ancient_janggo"               "1"
		"item_black_king_bar"               "1"
		"item_bottle"                       "1"
		"item_clarity"                      "1"
		"item_courier"                      "1"
		"item_diffusal_blade"               "1"
		"item_diffusal_blade_2"             "1"
		"item_dust"                         "1"
		"item_enchanted_mango"              "1"
		"item_flask"                        "1"
		"item_moon_shard"                   "1"
		"item_power_treads"                 "1"
		"item_slippers_of_halcyon"          "1"
		"item_tango"                        "1"
		"item_tango_single"                 "1"
		"item_tpscroll"                     "1"
		"item_travel_boots"                 "1"
		"item_travel_boots_2"               "1"
		"item_urn_of_shadows"               "1"
		"item_ward_dispenser"               "1"
		"item_ward_observer"                "1"
		"item_ward_sentry"                  "1"
		"keeper_of_the_light_illuminate_end"  "1" // wastes multicast cd
		"keeper_of_the_light_spirit_form_illuminate_end"  "1" // wastes multicast cd
		"kez_shodo_sai_parry_cancel"        "1" // wastes multicast cd
		"kunkka_return"                     "1" // wastes multicast cd
		"lich_dark_ritual"                  "1"
		"life_stealer_infest"               "1"
		"life_stealer_consume"              "1" // wastes multicast cd
		"lina_banana_redux"                 "1"
		"lina_coconut_redux"                "1"
		"lina_grapefruit_redux"             "1"
		"master_magic"                      "1"
		"meepo_megameepo_fling"             "1"
		"monkey_king_primal_spring"         "1" // bugs out
		"monkey_king_tree_dance"            "1" // bugs out
		"monkey_king_untransform"           "1" // wastes multicast cd
		"morphling_replicate"               "1" // bugs out
		"morphling_morph_replicate"         "1" // wastes multicast cd
		"nyx_assassin_burrow"               "1"
		"nyx_assassin_burrow_redux"         "1" // can cancel normal cast
		"nyx_assassin_unburrow"             "1" // wastes multicast cd
		"naga_siren_song_of_the_siren_cancel"  "1" // wastes multicast cd
		"pangolier_gyroshell_stop"          "1" // wastes multicast cd
		"pangolier_rollup_stop"             "1" // wastes multicast cd
		"phantom_assassin_phantom_strike"   "1"
		"phoenix_icarus_dive_stop"          "1" // wastes multicast cd
		"phoenix_sun_ray"                   "1"
		"phoenix_sun_ray_stop"              "1" // wastes multicast cd
		"phoenix_sun_ray_toggle_move"       "1" // wastes multicast cd
		"primal_beast_onslaught_release"    "1" // wastes multicast cd
		"puck_ethereal_jaunt"               "1" // wastes multicast cd
		"pudge_meat_hook"                   "1"
		"pudge_eject"                       "1" // wastes multicast cd
		"ringmaster_tame_the_beasts_crack"  "1" // wastes multicast cd
		"rubick_telekinesis_land"           "1" // wastes multicast cd
		"rubick_telekinesis_land_self"      "1" // wastes multicast cd
		"shadow_demon_shadow_poison_release"  "1" // wastes multicast cd
		"shredder_chakram"                  "1" // multiplies
		"shredder_chakram_2"                "1" // multiplies
		"shredder_return_chakram"           "1" // wastes multicast cd
		"shredder_return_chakram_2"         "1" // wastes multicast cd
		"shredder_timber_chain"             "1"
		"snapfire_spit_creep"               "1" // wastes multicast cd
		"sohei_flurry_of_blows"             "1" // can cancel normal cast
		"spectre_reality"                   "1" // wastes multicast cd
		"spell_lab_bfg"                     "1"
		"spell_lab_ggs"                     "1"
		"spell_lab_symbiotic"               "1"
		"spell_lab_taxi"                    "1"
		"techies_focused_detonate"          "1" // wastes multicast cd
		"techies_reactive_tazer_stop"       "1" // wastes multicast cd
		"tiny_toss_tree"                    "1" // wastes multicast cd
		"tusk_snowball"                     "1" // bugs out
		"tusk_launch_snowball"              "1" // wastes multicast cd
		"uther_Hurl_Hammer"                 "1"
		"visage_stone_form_self_cast"       "1" // wastes multicast cd
		//"witch_doctor_death_ward"         "1"
		"windrunner_focusfire_cancel"       "1" // wastes multicast cd
		"wisp_tether_break"                 "1" // wastes multicast cd
    }

    "noSpellEcho" {
        "ability_wards"                 "1"
        "ability_wards_op"                 "1"
        "alchemist_unstable_concoction" "1"
        "alchemist_unstable_concoction_throw"   "1"
        "angel_arena_tome_agi"  "1"
        "angel_arena_tome_agi_op"  "1"
        "angel_arena_tome_gods"  "1"
        "angel_arena_tome_gods_op"  "1"
        "angel_arena_tome_int"  "1"
        "angel_arena_tome_int_op"  "1"
        "angel_arena_tome_lvlup"  "1"
        "angel_arena_tome_lvlup_op"  "1"
        "angel_arena_tome_med"  "1"
        "angel_arena_tome_med_op"  "1"
        "angel_arena_tome_str"  "1"
        "angel_arena_tome_str_op"  "1"
        "antimage_blink"    "1"
        "arc_warden_tempest_double" "1"
        "furion_teleportation" "1"
        "hawkeye_ricochet"            "1"
        "hoodwink_sharpshooter" "1"
        "hoodwink_sharpshooter_release" "1"
        "juggernaut_omni_slash" "1"
        "lina_banana_redux"     "1"
        "lina_coconut_redux"    "1"
        "lina_grapefruit_redux" "1"
        "master_magic"  "1"
        "monkey_king_wukongs_command"            "1"
        "phoenix_fire_spirits"  "1"
        "phoenix_icarus_dive"   "1"
        "phoenix_icarus_dive_stop"  "1"
        "phoenix_launch_fire_spirit"    "1"
        "phoenix_sun_ray"   "1"
        "phoenix_sun_ray_stop"  "1"
        "phoenix_sun_ray_toggle_move"   "1"
        "phoenix_supernova" "1"
        "queenofpain_blink" "1"
        "rubick_telekinesis_land"   "1"
        "shredder_chakram"  "1"
        "shredder_chakram_2"    "1"
        "shredder_chakram_return"   "1"
        "shredder_return_chakram_2" "1"
        "spell_lab_symbiotic"  "1"
        "vengefulspirit_nether_swap"    "1"
        "witch_doctor_paralyzing_cask"            "1"
        //"android_pocket_factory"            "1"
    }

    // Abiltiies that won't have their cooldowns lowered by our patch
    "noWitchcraft" {
        "chi_strike"                    "1"
        "death_prophet_carrion_swarm"   "1"
        "death_prophet_silence"         "1"
    }

    // Skills that are never allowed on a tower
    "noTowerAlways" {
        "pudge_flesh_heap"              "1"
        "riki_permanent_invisibility"   "1" //Towers become unclickable
        "troll_warlord_berserkers_rage" "1"
        "vengefulspirit_command_aura"   "1"
    }

    // Stop tower from getting these abilities
    "noTower" {
        "brewmaster_drunken_brawler"    "#noTowerOP"
        "dragon_knight_dragon_blood"    "#noTowerLongGame"
        "faceless_void_backtrack"       "#noTowerOP"
        "life_stealer_feast"            "#noTowerOP"
        "lod_item_heart"                "#noTowerLongGame"
        "lod_item_helm_of_the_dominator""#noTowerLongGame"
        "lod_item_lifesteal"            "#noTowerLongGame"
        "lod_item_mask_of_madness"      "#noTowerLongGame"
        "lod_item_satanic"              "#noTowerLongGame"
        "medusa_split_shot"             "#noTowerActivate"
        "necrolyte_sadist"              "#noTowerOP"
        "phantom_assassin_blur"         "#noTowerOP"
        "pudge_flesh_heap"              "#noTowerCrash"
        "riki_permanent_invisibility"   "#noTowerNoAttack"
        "shredder_reactive_armor"       "#noTowerLongGame"
        "slark_shadow_dance"            "#noTowerLongGame"
        "troll_warlord_berserkers_rage" "#noTowerCrash"
        "ursa_fury_swipes"              "#noTowerOP"
        "vengefulspirit_command_aura"   "#noTowerCrash"
    }

    // Skills that can not be used on bears
    "noBear" {
        "pudge_flesh_heap"                  "1"
        "troll_warlord_berserkers_rage"     "1"
        "vengefulspirit_command_aura"       "1"
    }

    // timelock geminate attack
    "timelockgemi" {
        "faceless_void_time_lock"  "1"
        "weaver_geminate_attack" "1"
    }
}
