// We use this KV to set the owners of custom spells (numbers are HeroIDs of owners)
"Owners" {
    // Invoker
    "invoker_alacrity_lod"                      "74"
    "invoker_chaos_meteor_lod"                  "74"
    "invoker_cold_snap_lod"                     "74"
    "invoker_deafening_blast_lod"               "74"
    "invoker_emp_lod"                           "74"
    "invoker_forge_spirit_lod"                  "74"
    "invoker_ghost_walk_lod"                    "74"
    "invoker_ice_wall_lod"                      "74"
    "invoker_sun_strike_lod"                    "74"
    "invoker_tornado_lod"                       "74"

    // Legion Commander
    "holdout_gladiators_unite"                  "104"

    // Zuus
    //"zuus_thundergods_vengeance"                "22"

    // Jugernaunt
    //"holdout_omnislash"                         "8"

    // Drow
    //"holdout_multishot"                         "6"

    // Sven
    //"holdout_gods_strength"                     "18"

    // Crystal Maiden
    //"holdout_arcane_aura"                       "5"

    // Venomancer
    "holdout_scourge_ward"                      "40"

	"abyssal_underlord_atrophy_aura_op"           "108"
	"abyssal_underlord_dark_rift_op"              "108"
	"alchemist_goblins_greed_op"                  "73"
	"arc_warden_tempest_double_op"                "113"
	"batrider_flamebreak_op"                      "65"
	"clinkz_burning_army_op"                      "56"
	"dark_seer_vacuum_op"                         "55"
	"disruptor_glimpse_OP"                        "87"
	"disruptor_kinetic_field_OP"                  "87"
	"faceless_void_chronosphere_op"               "41"
	"faceless_void_chronosphere_redux"            "41"
	"grimstroke_soul_chain_friendly"              "121"
	"grimstroke_soul_chain_op"                    "121"
	"imba_tower_plasma_field"                     "15"
	"invoker_chaos_meteor_op"                     "74"
	"invoker_sun_strike_lod_op"                   "74"
	"keeper_of_the_light_chakra_magic_cooldown"   "90"
	"legion_commander_duel_redux"                 "104"
	"lone_druid_savage_roar_op"                   "80"
	"mars_arena_of_blood_op"                      "129"
	"mega_call_down"                              "72"
	"mega_chronosphere"                           "41"
	"mega_suicide"                                "105"
	"mirana_invis_redux"                          "9"
	"ogre_magi_bloodlust_op"                      "84"
	"ogre_magi_bloodlust_reverse"                 "84"
	"pangolier_swashbuckle_op"                    "120"
	"shadow_shaman_mass_serpent_ward_redux"       "27"
	"shredder_reactive_armor_op"                  "98"
	"templar_assassin_psi_blades_op"              "46"
	"tinker_heat_seeking_missile_redux"           "34"
	"tusk_walrus_kick_op"                         "100"
	"undying_soul_rip_op"                         "85"
	//"axe_berserkers_call_op"                      "2"
	//"bounty_hunter_jinada_op"                     "62"
	//"bristleback_warpath_op"                      "99"
	//"death_prophet_witchcraft_op"                 "43"
	//"dragon_knight_dragon_blood_OP"               "49"
	//"floor_is_lava"                               "64"
	//"lich_chain_frost_op"                         "31"
	//"mega_eclipse"                                "48"
	//"mega_flare"                                  "101"
	//"mega_freezing_field"                         "5"
	//"mega_omni_slash"                             "8"
	//"nevermore_necromastery_op"                   "11"
	//"windrunner_gale_force_op"                    "21"
	//"zuus_arc_lightning_op"                       "22"
	//"zuus_lightning_bolt_global"                  "22"
}
