"sounds" {
	"hero_sounds" {
		"abaddon" "1"
		"abyssal_underlord" "1"
		"alchemist" "1"
		"ancient_apparition" "1"
		"antimage" "1"
		"arc_warden" "1"
		"axe" "1"
		"bane" "1"
		"batrider" "1"
		"beastmaster" "1"
		"bloodseeker" "1"
		"bounty_hunter" "1"
		"brewmaster" "1"
		"bristleback" "1"
		"broodmother" "1"
		"centaur" "1"
		"chaos_knight" "1"
		"chen" "1"
		"clinkz" "1"
		"crystalmaiden" "1"
		"dark_seer" "1"
		"dark_willow" "1"
		"dawnbreaker" "1"
		"dazzle"	"1"
		"death_prophet" "1"
		"disruptor" "1"
		"doombringer" "1"
		"dragon_knight" "1"
		"drowranger" "1"
		"earth_spirit" "1"
		"earthshaker" "1"
		"elder_titan" "1"
		"ember_spirit" "1"
		"enchantress" "1"
		"enigma" "1"
		"faceless_void" "1"
		"furion" "1"
		"grimstroke" "1"
		"gyrocopter" "1"
		"hoodwink" "1"
		"huskar" "1"
		"invoker" "1"
		"jakiro" "1"
		"juggernaut" "1"
		"keeper_of_the_light" "1"
		"kez" "1"
		"kunkka" "1"
		"largo" "1"
		"legion_commander" "1"
		"leshrac" "1"
		"lich" "1"
		"life_stealer" "1"
		"lina" "1"
		"lion" "1"
		"lone_druid" "1"
		"luna" "1"
		"lycan" "1"
		"magnataur" "1"
		"marci" "1"
		"mars" "1"
		"medusa" "1"
		"meepo" "1"
		"mirana" "1"
		"monkey_king" "1"
		"morphling" "1"
		"muerta" "1"
		"naga_siren" "1"
		"necrolyte" "1"
		"nevermore" "1"
		"nightstalker" "1"
		"nyx_assassin" "1"
		"obsidian_destroyer" "1"
		"ogre_magi" "1"
		"omniknight" "1"
		"oracle" "1"
		"pangolier" "1"
		"phantom_assassin" "1"
		"phantom_lancer" "1"
		"phoenix" "1"
		"primal_beast" "1"
		"puck" "1"
		"pudge" "1"
		"pugna" "1"
		"queenofpain" "1"
		"rattletrap" "1"
		"razor" "1"
		"riki" "1"
		"ringmaster" "1"
		"rubick" "1"
		"sandking" "1"
		"shadow_demon" "1"
		"shadowshaman" "1"
		"shredder" "1"
		"silencer" "1"
		"skeletonking" "1"
		"skywrath_mage" "1"
		"slardar" "1"
		"slark" "1"
		"snapfire" "1"
		"sniper" "1"
		"spectre" "1"
		"spirit_breaker" "1"
		"stormspirit" "1"
		"sven" "1"
		"techies" "1"
		"templar_assassin" "1"
		"terrorblade" "1"
		"tidehunter" "1"
		"tinker" "1"
		"tiny" "1"
		"treant" "1"
		"troll_warlord" "1"
		"tusk" "1"
		"undying" "1"
		"ursa" "1"
		"vengefulspirit" "1"
		"venomancer"  "1"
		"viper" "1"
		"visage" "1"
		"void_spirit" "1"
		"warlock" "1"
		"weaver" "1"
		"windrunner" "1"
		"winter_wyvern" "1"
		"wisp" "1"
		"witchdoctor" "1"
		"zuus" "1"
	}

    "game_option_host" {
        "announcer_ann_custom_mode_05" "1"
    }

    "game_option_player" {
        "announcer_announcer_intl2012_usher_03" "1"
    }

    "game_picking_phase" {
        "announcer_announcer_type_ability_draft_01" "1"
        "announcer_ann_custom_draft_01" "1"
    }

    "game_30_sec_remaining" {
        "announcer_ann_custom_timer_sec_30" "1"
    }

    "game_15_sec_remaining" {
        "announcer_ann_custom_timer_sec_15" "1"
    }

    "game_10_sec_remaining" {
        "announcer_ann_custom_timer_sec_10" "1"
    }

    "game_6_sec_remaining" {
        "announcer_announcer_choose_hero" "1"
    }

    "game_error_alert" {
        "announcer_ann_custom_sports_02" "1"
        "announcer_ann_custom_sports_03" "1"
        "announcer_ann_custom_sports_04" "1"
        "announcer_ann_custom_bad_01" "1"
    }

    "game_out_of_points" {
        "announcer_ann_custom_generic_alert_05" "1"
        "announcer_ann_custom_generic_alert_06" "1"
    }

    "game_ban_started" {
        "announcer_announcer_ban_yr" "1"
    }

    "game_review_phase" {
        "announcer_announcer_battle_prepare_01" "1"
        "announcer_announcer_welcome_08" "1"
    }
}
